/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.moov.openapi.models.operations;

import io.moov.openapi.models.components.Versions;
import io.moov.openapi.utils.Utils;
import java.util.Optional;

public class PingRequestBuilder {

    private PingSecurity security;
    private Optional<? extends Versions> xMoovVersion = Optional.empty();
    private final SDKMethodInterfaces.MethodCallPing sdk;

    public PingRequestBuilder(SDKMethodInterfaces.MethodCallPing sdk) {
        this.sdk = sdk;
    }

    public PingRequestBuilder security(PingSecurity security) {
        Utils.checkNotNull(security, "security");
        this.security = security;
        return this;
    }
                
    public PingRequestBuilder xMoovVersion(Versions xMoovVersion) {
        Utils.checkNotNull(xMoovVersion, "xMoovVersion");
        this.xMoovVersion = Optional.of(xMoovVersion);
        return this;
    }

    public PingRequestBuilder xMoovVersion(Optional<? extends Versions> xMoovVersion) {
        Utils.checkNotNull(xMoovVersion, "xMoovVersion");
        this.xMoovVersion = xMoovVersion;
        return this;
    }

    public PingResponse call() throws Exception {

        return sdk.ping(
            security,
            xMoovVersion);
    }
}
