/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.moov.sdk.models.operations;

import static io.moov.sdk.operations.Operations.RequestOperation;

import io.moov.sdk.SDKConfiguration;
import io.moov.sdk.operations.DeleteRepresentative;
import io.moov.sdk.utils.Utils;
import java.lang.Exception;
import java.lang.String;

public class DeleteRepresentativeRequestBuilder {

    private String accountID;
    private String representativeID;
    private final SDKConfiguration sdkConfiguration;

    public DeleteRepresentativeRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public DeleteRepresentativeRequestBuilder accountID(String accountID) {
        Utils.checkNotNull(accountID, "accountID");
        this.accountID = accountID;
        return this;
    }

    public DeleteRepresentativeRequestBuilder representativeID(String representativeID) {
        Utils.checkNotNull(representativeID, "representativeID");
        this.representativeID = representativeID;
        return this;
    }


    private DeleteRepresentativeRequest buildRequest() {

        DeleteRepresentativeRequest request = new DeleteRepresentativeRequest(accountID,
            representativeID);

        return request;
    }

    public DeleteRepresentativeResponse call() throws Exception {
        
        RequestOperation<DeleteRepresentativeRequest, DeleteRepresentativeResponse> operation
              = new DeleteRepresentative.Sync(sdkConfiguration);
        DeleteRepresentativeRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
