/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.moov.sdk.models.operations;

import io.moov.sdk.models.components.Versions;
import io.moov.sdk.utils.Utils;
import java.lang.String;
import java.util.Optional;

public class GetAdjustmentRequestBuilder {

    private GetAdjustmentSecurity security;
    private Optional<? extends Versions> xMoovVersion = Optional.empty();
    private String accountID;
    private String adjustmentID;
    private final SDKMethodInterfaces.MethodCallGetAdjustment sdk;

    public GetAdjustmentRequestBuilder(SDKMethodInterfaces.MethodCallGetAdjustment sdk) {
        this.sdk = sdk;
    }

    public GetAdjustmentRequestBuilder security(GetAdjustmentSecurity security) {
        Utils.checkNotNull(security, "security");
        this.security = security;
        return this;
    }
                
    public GetAdjustmentRequestBuilder xMoovVersion(Versions xMoovVersion) {
        Utils.checkNotNull(xMoovVersion, "xMoovVersion");
        this.xMoovVersion = Optional.of(xMoovVersion);
        return this;
    }

    public GetAdjustmentRequestBuilder xMoovVersion(Optional<? extends Versions> xMoovVersion) {
        Utils.checkNotNull(xMoovVersion, "xMoovVersion");
        this.xMoovVersion = xMoovVersion;
        return this;
    }

    public GetAdjustmentRequestBuilder accountID(String accountID) {
        Utils.checkNotNull(accountID, "accountID");
        this.accountID = accountID;
        return this;
    }

    public GetAdjustmentRequestBuilder adjustmentID(String adjustmentID) {
        Utils.checkNotNull(adjustmentID, "adjustmentID");
        this.adjustmentID = adjustmentID;
        return this;
    }

    public GetAdjustmentResponse call() throws Exception {

        return sdk.get(
            security,
            xMoovVersion,
            accountID,
            adjustmentID);
    }
}
