/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.moov.sdk.models.operations;

import io.moov.sdk.models.components.Versions;
import io.moov.sdk.utils.Utils;
import java.lang.String;
import java.util.Optional;

public class GetWalletTransactionRequestBuilder {

    private GetWalletTransactionSecurity security;
    private Optional<? extends Versions> xMoovVersion = Optional.empty();
    private String accountID;
    private String walletID;
    private String transactionID;
    private final SDKMethodInterfaces.MethodCallGetWalletTransaction sdk;

    public GetWalletTransactionRequestBuilder(SDKMethodInterfaces.MethodCallGetWalletTransaction sdk) {
        this.sdk = sdk;
    }

    public GetWalletTransactionRequestBuilder security(GetWalletTransactionSecurity security) {
        Utils.checkNotNull(security, "security");
        this.security = security;
        return this;
    }
                
    public GetWalletTransactionRequestBuilder xMoovVersion(Versions xMoovVersion) {
        Utils.checkNotNull(xMoovVersion, "xMoovVersion");
        this.xMoovVersion = Optional.of(xMoovVersion);
        return this;
    }

    public GetWalletTransactionRequestBuilder xMoovVersion(Optional<? extends Versions> xMoovVersion) {
        Utils.checkNotNull(xMoovVersion, "xMoovVersion");
        this.xMoovVersion = xMoovVersion;
        return this;
    }

    public GetWalletTransactionRequestBuilder accountID(String accountID) {
        Utils.checkNotNull(accountID, "accountID");
        this.accountID = accountID;
        return this;
    }

    public GetWalletTransactionRequestBuilder walletID(String walletID) {
        Utils.checkNotNull(walletID, "walletID");
        this.walletID = walletID;
        return this;
    }

    public GetWalletTransactionRequestBuilder transactionID(String transactionID) {
        Utils.checkNotNull(transactionID, "transactionID");
        this.transactionID = transactionID;
        return this;
    }

    public GetWalletTransactionResponse call() throws Exception {

        return sdk.getWalletTransaction(
            security,
            xMoovVersion,
            accountID,
            walletID,
            transactionID);
    }
}
