/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.moov.sdk.models.operations;

import com.fasterxml.jackson.core.type.TypeReference;
import io.moov.sdk.models.components.LinkAccountTerminalApplication;
import io.moov.sdk.utils.LazySingletonValue;
import io.moov.sdk.utils.Utils;
import java.lang.Exception;
import java.lang.String;
import java.util.Optional;

public class LinkAccountTerminalApplicationRequestBuilder {

    private Optional<String> xMoovVersion = Utils.readDefaultOrConstValue(
                            "xMoovVersion",
                            "\"v2024.01.00\"",
                            new TypeReference<Optional<String>>() {});
    private String accountID;
    private LinkAccountTerminalApplication linkAccountTerminalApplication;
    private final SDKMethodInterfaces.MethodCallLinkAccountTerminalApplication sdk;

    public LinkAccountTerminalApplicationRequestBuilder(SDKMethodInterfaces.MethodCallLinkAccountTerminalApplication sdk) {
        this.sdk = sdk;
    }
                
    public LinkAccountTerminalApplicationRequestBuilder xMoovVersion(String xMoovVersion) {
        Utils.checkNotNull(xMoovVersion, "xMoovVersion");
        this.xMoovVersion = Optional.of(xMoovVersion);
        return this;
    }

    public LinkAccountTerminalApplicationRequestBuilder xMoovVersion(Optional<String> xMoovVersion) {
        Utils.checkNotNull(xMoovVersion, "xMoovVersion");
        this.xMoovVersion = xMoovVersion;
        return this;
    }

    public LinkAccountTerminalApplicationRequestBuilder accountID(String accountID) {
        Utils.checkNotNull(accountID, "accountID");
        this.accountID = accountID;
        return this;
    }

    public LinkAccountTerminalApplicationRequestBuilder linkAccountTerminalApplication(LinkAccountTerminalApplication linkAccountTerminalApplication) {
        Utils.checkNotNull(linkAccountTerminalApplication, "linkAccountTerminalApplication");
        this.linkAccountTerminalApplication = linkAccountTerminalApplication;
        return this;
    }

    public LinkAccountTerminalApplicationResponse call() throws Exception {
        if (xMoovVersion == null) {
            xMoovVersion = _SINGLETON_VALUE_XMoovVersion.value();
        }
        return sdk.link(
            xMoovVersion,
            accountID,
            linkAccountTerminalApplication);
    }

    private static final LazySingletonValue<Optional<String>> _SINGLETON_VALUE_XMoovVersion =
            new LazySingletonValue<>(
                    "xMoovVersion",
                    "\"v2024.01.00\"",
                    new TypeReference<Optional<String>>() {});
}
