/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.moov.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.moov.sdk.utils.SpeakeasyMetadata;
import io.moov.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;

public class ListDisputeEvidenceRequest {

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=accountID")
    private String accountID;

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=disputeID")
    private String disputeID;

    @JsonCreator
    public ListDisputeEvidenceRequest(
            String accountID,
            String disputeID) {
        Utils.checkNotNull(accountID, "accountID");
        Utils.checkNotNull(disputeID, "disputeID");
        this.accountID = accountID;
        this.disputeID = disputeID;
    }

    @JsonIgnore
    public String accountID() {
        return accountID;
    }

    @JsonIgnore
    public String disputeID() {
        return disputeID;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    public ListDisputeEvidenceRequest withAccountID(String accountID) {
        Utils.checkNotNull(accountID, "accountID");
        this.accountID = accountID;
        return this;
    }

    public ListDisputeEvidenceRequest withDisputeID(String disputeID) {
        Utils.checkNotNull(disputeID, "disputeID");
        this.disputeID = disputeID;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListDisputeEvidenceRequest other = (ListDisputeEvidenceRequest) o;
        return 
            Objects.deepEquals(this.accountID, other.accountID) &&
            Objects.deepEquals(this.disputeID, other.disputeID);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            accountID,
            disputeID);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListDisputeEvidenceRequest.class,
                "accountID", accountID,
                "disputeID", disputeID);
    }
    
    public final static class Builder {
 
        private String accountID;
 
        private String disputeID;
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder accountID(String accountID) {
            Utils.checkNotNull(accountID, "accountID");
            this.accountID = accountID;
            return this;
        }

        public Builder disputeID(String disputeID) {
            Utils.checkNotNull(disputeID, "disputeID");
            this.disputeID = disputeID;
            return this;
        }
        
        public ListDisputeEvidenceRequest build() {
            return new ListDisputeEvidenceRequest(
                accountID,
                disputeID);
        }
    }
}
