/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.moov.sdk.models.operations;

import io.moov.sdk.models.components.Versions;
import io.moov.sdk.utils.Utils;
import java.util.Optional;

public class ListOnboardingInvitesRequestBuilder {

    private Optional<? extends Versions> xMoovVersion = Optional.empty();
    private final SDKMethodInterfaces.MethodCallListOnboardingInvites sdk;

    public ListOnboardingInvitesRequestBuilder(SDKMethodInterfaces.MethodCallListOnboardingInvites sdk) {
        this.sdk = sdk;
    }
                
    public ListOnboardingInvitesRequestBuilder xMoovVersion(Versions xMoovVersion) {
        Utils.checkNotNull(xMoovVersion, "xMoovVersion");
        this.xMoovVersion = Optional.of(xMoovVersion);
        return this;
    }

    public ListOnboardingInvitesRequestBuilder xMoovVersion(Optional<? extends Versions> xMoovVersion) {
        Utils.checkNotNull(xMoovVersion, "xMoovVersion");
        this.xMoovVersion = xMoovVersion;
        return this;
    }

    public ListOnboardingInvitesResponse call() throws Exception {

        return sdk.listInvites(
            xMoovVersion);
    }
}
