/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.moov.sdk.models.operations;

import static io.moov.sdk.operations.Operations.RequestOperation;

import io.moov.sdk.SDKConfiguration;
import io.moov.sdk.models.components.UpsertUnderwriting;
import io.moov.sdk.operations.SaveUnderwriting;
import io.moov.sdk.utils.Headers;
import io.moov.sdk.utils.Utils;
import java.lang.String;

public class SaveUnderwritingRequestBuilder {

    private String accountID;
    private UpsertUnderwriting upsertUnderwriting;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public SaveUnderwritingRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public SaveUnderwritingRequestBuilder accountID(String accountID) {
        Utils.checkNotNull(accountID, "accountID");
        this.accountID = accountID;
        return this;
    }

    public SaveUnderwritingRequestBuilder upsertUnderwriting(UpsertUnderwriting upsertUnderwriting) {
        Utils.checkNotNull(upsertUnderwriting, "upsertUnderwriting");
        this.upsertUnderwriting = upsertUnderwriting;
        return this;
    }


    private SaveUnderwritingRequest buildRequest() {

        SaveUnderwritingRequest request = new SaveUnderwritingRequest(accountID,
            upsertUnderwriting);

        return request;
    }

    public SaveUnderwritingResponse call() {
        
        RequestOperation<SaveUnderwritingRequest, SaveUnderwritingResponse> operation
              = new SaveUnderwriting.Sync(sdkConfiguration, _headers);
        SaveUnderwritingRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
