/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.moov.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.moov.sdk.models.components.UpdateWebhook;
import io.moov.sdk.utils.SpeakeasyMetadata;
import io.moov.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;


public class UpdateWebhookRequest {

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=webhookID")
    private String webhookID;


    @SpeakeasyMetadata("request:mediaType=application/json")
    private UpdateWebhook updateWebhook;

    @JsonCreator
    public UpdateWebhookRequest(
            String webhookID,
            UpdateWebhook updateWebhook) {
        Utils.checkNotNull(webhookID, "webhookID");
        Utils.checkNotNull(updateWebhook, "updateWebhook");
        this.webhookID = webhookID;
        this.updateWebhook = updateWebhook;
    }

    @JsonIgnore
    public String webhookID() {
        return webhookID;
    }

    @JsonIgnore
    public UpdateWebhook updateWebhook() {
        return updateWebhook;
    }

    public static Builder builder() {
        return new Builder();
    }


    public UpdateWebhookRequest withWebhookID(String webhookID) {
        Utils.checkNotNull(webhookID, "webhookID");
        this.webhookID = webhookID;
        return this;
    }

    public UpdateWebhookRequest withUpdateWebhook(UpdateWebhook updateWebhook) {
        Utils.checkNotNull(updateWebhook, "updateWebhook");
        this.updateWebhook = updateWebhook;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateWebhookRequest other = (UpdateWebhookRequest) o;
        return 
            Utils.enhancedDeepEquals(this.webhookID, other.webhookID) &&
            Utils.enhancedDeepEquals(this.updateWebhook, other.updateWebhook);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            webhookID, updateWebhook);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateWebhookRequest.class,
                "webhookID", webhookID,
                "updateWebhook", updateWebhook);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String webhookID;

        private UpdateWebhook updateWebhook;

        private Builder() {
          // force use of static builder() method
        }


        public Builder webhookID(String webhookID) {
            Utils.checkNotNull(webhookID, "webhookID");
            this.webhookID = webhookID;
            return this;
        }


        public Builder updateWebhook(UpdateWebhook updateWebhook) {
            Utils.checkNotNull(updateWebhook, "updateWebhook");
            this.updateWebhook = updateWebhook;
            return this;
        }

        public UpdateWebhookRequest build() {

            return new UpdateWebhookRequest(
                webhookID, updateWebhook);
        }

    }
}
