workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    latest:
        inputs:
            - location: registry.speakeasyapi.dev/moov/moov/api-v2026.01.00
              type: openapi
        registry:
            location: registry.speakeasyapi.dev/moov/moov/java-v2026.01.00
targets:
    latest:
        target: java
        source: latest
        publish:
            java:
                ossrhUsername: $ossrh_username
                ossrhPassword: $ossrh_password
                gpgSecretKey: $java_gpg_secret_key
                gpgPassPhrase: $java_gpg_passphrase
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/moov/moov/v2026.01.00-java-code-samples
            labelOverride:
                fixedValue: Java (SDK)
            blocking: false
