workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    dev:
        inputs:
            - location: registry.speakeasyapi.dev/moov/moov/api-dev
        registry:
            location: registry.speakeasyapi.dev/moov/moov/java-dev
targets:
    latest:
        target: java
        source: dev
        publish:
            java:
                ossrhUsername: $ossrh_username
                ossrhPassword: $ossrh_password
                gpgSecretKey: $java_gpg_secret_key
                gpgPassPhrase: $java_gpg_passphrase
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/moov/moov/dev-java-code-samples
            labelOverride:
                fixedValue: Java (SDK)
            blocking: false
