/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.moov.api.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.moov.api.models.components.ApplePayMerchantDomains;
import io.moov.api.utils.Response;
import io.moov.api.utils.Utils;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;


public class RegisterApplePayMerchantDomainsResponse implements Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * The request completed successfully.
     */
    private Optional<? extends ApplePayMerchantDomains> applePayMerchantDomains;

    @JsonCreator
    public RegisterApplePayMerchantDomainsResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends ApplePayMerchantDomains> applePayMerchantDomains) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(applePayMerchantDomains, "applePayMerchantDomains");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.applePayMerchantDomains = applePayMerchantDomains;
    }
    
    public RegisterApplePayMerchantDomainsResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse, Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * The request completed successfully.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<ApplePayMerchantDomains> applePayMerchantDomains() {
        return (Optional<ApplePayMerchantDomains>) applePayMerchantDomains;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * HTTP response content type for this operation
     */
    public RegisterApplePayMerchantDomainsResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public RegisterApplePayMerchantDomainsResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public RegisterApplePayMerchantDomainsResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * The request completed successfully.
     */
    public RegisterApplePayMerchantDomainsResponse withApplePayMerchantDomains(ApplePayMerchantDomains applePayMerchantDomains) {
        Utils.checkNotNull(applePayMerchantDomains, "applePayMerchantDomains");
        this.applePayMerchantDomains = Optional.ofNullable(applePayMerchantDomains);
        return this;
    }

    /**
     * The request completed successfully.
     */
    public RegisterApplePayMerchantDomainsResponse withApplePayMerchantDomains(Optional<? extends ApplePayMerchantDomains> applePayMerchantDomains) {
        Utils.checkNotNull(applePayMerchantDomains, "applePayMerchantDomains");
        this.applePayMerchantDomains = applePayMerchantDomains;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RegisterApplePayMerchantDomainsResponse other = (RegisterApplePayMerchantDomainsResponse) o;
        return 
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse) &&
            Objects.deepEquals(this.applePayMerchantDomains, other.applePayMerchantDomains);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            contentType,
            statusCode,
            rawResponse,
            applePayMerchantDomains);
    }
    
    @Override
    public String toString() {
        return Utils.toString(RegisterApplePayMerchantDomainsResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "applePayMerchantDomains", applePayMerchantDomains);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends ApplePayMerchantDomains> applePayMerchantDomains = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        /**
         * The request completed successfully.
         */
        public Builder applePayMerchantDomains(ApplePayMerchantDomains applePayMerchantDomains) {
            Utils.checkNotNull(applePayMerchantDomains, "applePayMerchantDomains");
            this.applePayMerchantDomains = Optional.ofNullable(applePayMerchantDomains);
            return this;
        }

        /**
         * The request completed successfully.
         */
        public Builder applePayMerchantDomains(Optional<? extends ApplePayMerchantDomains> applePayMerchantDomains) {
            Utils.checkNotNull(applePayMerchantDomains, "applePayMerchantDomains");
            this.applePayMerchantDomains = applePayMerchantDomains;
            return this;
        }
        
        public RegisterApplePayMerchantDomainsResponse build() {
            return new RegisterApplePayMerchantDomainsResponse(
                contentType,
                statusCode,
                rawResponse,
                applePayMerchantDomains);
        }
    }
}

