/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.moov.api.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.moov.api.models.components.UpdateEvidence;
import io.moov.api.models.components.Versions;
import io.moov.api.utils.SpeakeasyMetadata;
import io.moov.api.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Objects;
import java.util.Optional;


public class UpdateDisputeEvidenceRequest {

    /**
     * Specify an API version.
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=x-moov-version")
    private Optional<? extends Versions> xMoovVersion;

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=accountID")
    private String accountID;

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=disputeID")
    private String disputeID;

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=evidenceID")
    private String evidenceID;

    @SpeakeasyMetadata("request:mediaType=application/json")
    private UpdateEvidence updateEvidence;

    @JsonCreator
    public UpdateDisputeEvidenceRequest(
            Optional<? extends Versions> xMoovVersion,
            String accountID,
            String disputeID,
            String evidenceID,
            UpdateEvidence updateEvidence) {
        Utils.checkNotNull(xMoovVersion, "xMoovVersion");
        Utils.checkNotNull(accountID, "accountID");
        Utils.checkNotNull(disputeID, "disputeID");
        Utils.checkNotNull(evidenceID, "evidenceID");
        Utils.checkNotNull(updateEvidence, "updateEvidence");
        this.xMoovVersion = xMoovVersion;
        this.accountID = accountID;
        this.disputeID = disputeID;
        this.evidenceID = evidenceID;
        this.updateEvidence = updateEvidence;
    }
    
    public UpdateDisputeEvidenceRequest(
            String accountID,
            String disputeID,
            String evidenceID,
            UpdateEvidence updateEvidence) {
        this(Optional.empty(), accountID, disputeID, evidenceID, updateEvidence);
    }

    /**
     * Specify an API version.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Versions> xMoovVersion() {
        return (Optional<Versions>) xMoovVersion;
    }

    @JsonIgnore
    public String accountID() {
        return accountID;
    }

    @JsonIgnore
    public String disputeID() {
        return disputeID;
    }

    @JsonIgnore
    public String evidenceID() {
        return evidenceID;
    }

    @JsonIgnore
    public UpdateEvidence updateEvidence() {
        return updateEvidence;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * Specify an API version.
     */
    public UpdateDisputeEvidenceRequest withXMoovVersion(Versions xMoovVersion) {
        Utils.checkNotNull(xMoovVersion, "xMoovVersion");
        this.xMoovVersion = Optional.ofNullable(xMoovVersion);
        return this;
    }

    /**
     * Specify an API version.
     */
    public UpdateDisputeEvidenceRequest withXMoovVersion(Optional<? extends Versions> xMoovVersion) {
        Utils.checkNotNull(xMoovVersion, "xMoovVersion");
        this.xMoovVersion = xMoovVersion;
        return this;
    }

    public UpdateDisputeEvidenceRequest withAccountID(String accountID) {
        Utils.checkNotNull(accountID, "accountID");
        this.accountID = accountID;
        return this;
    }

    public UpdateDisputeEvidenceRequest withDisputeID(String disputeID) {
        Utils.checkNotNull(disputeID, "disputeID");
        this.disputeID = disputeID;
        return this;
    }

    public UpdateDisputeEvidenceRequest withEvidenceID(String evidenceID) {
        Utils.checkNotNull(evidenceID, "evidenceID");
        this.evidenceID = evidenceID;
        return this;
    }

    public UpdateDisputeEvidenceRequest withUpdateEvidence(UpdateEvidence updateEvidence) {
        Utils.checkNotNull(updateEvidence, "updateEvidence");
        this.updateEvidence = updateEvidence;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateDisputeEvidenceRequest other = (UpdateDisputeEvidenceRequest) o;
        return 
            Objects.deepEquals(this.xMoovVersion, other.xMoovVersion) &&
            Objects.deepEquals(this.accountID, other.accountID) &&
            Objects.deepEquals(this.disputeID, other.disputeID) &&
            Objects.deepEquals(this.evidenceID, other.evidenceID) &&
            Objects.deepEquals(this.updateEvidence, other.updateEvidence);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            xMoovVersion,
            accountID,
            disputeID,
            evidenceID,
            updateEvidence);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateDisputeEvidenceRequest.class,
                "xMoovVersion", xMoovVersion,
                "accountID", accountID,
                "disputeID", disputeID,
                "evidenceID", evidenceID,
                "updateEvidence", updateEvidence);
    }
    
    public final static class Builder {
 
        private Optional<? extends Versions> xMoovVersion = Optional.empty();
 
        private String accountID;
 
        private String disputeID;
 
        private String evidenceID;
 
        private UpdateEvidence updateEvidence;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Specify an API version.
         */
        public Builder xMoovVersion(Versions xMoovVersion) {
            Utils.checkNotNull(xMoovVersion, "xMoovVersion");
            this.xMoovVersion = Optional.ofNullable(xMoovVersion);
            return this;
        }

        /**
         * Specify an API version.
         */
        public Builder xMoovVersion(Optional<? extends Versions> xMoovVersion) {
            Utils.checkNotNull(xMoovVersion, "xMoovVersion");
            this.xMoovVersion = xMoovVersion;
            return this;
        }

        public Builder accountID(String accountID) {
            Utils.checkNotNull(accountID, "accountID");
            this.accountID = accountID;
            return this;
        }

        public Builder disputeID(String disputeID) {
            Utils.checkNotNull(disputeID, "disputeID");
            this.disputeID = disputeID;
            return this;
        }

        public Builder evidenceID(String evidenceID) {
            Utils.checkNotNull(evidenceID, "evidenceID");
            this.evidenceID = evidenceID;
            return this;
        }

        public Builder updateEvidence(UpdateEvidence updateEvidence) {
            Utils.checkNotNull(updateEvidence, "updateEvidence");
            this.updateEvidence = updateEvidence;
            return this;
        }
        
        public UpdateDisputeEvidenceRequest build() {
            return new UpdateDisputeEvidenceRequest(
                xMoovVersion,
                accountID,
                disputeID,
                evidenceID,
                updateEvidence);
        }
    }
}

