/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */


package io.moov.sdk.models.components;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
public enum ApplePayPaymentMethodPaymentMethodType {
    APPLE_PAY("apple-pay");

    @JsonValue
    private final String value;

    private ApplePayPaymentMethodPaymentMethodType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<ApplePayPaymentMethodPaymentMethodType> fromValue(String value) {
        for (ApplePayPaymentMethodPaymentMethodType o: ApplePayPaymentMethodPaymentMethodType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}
