/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.moov.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.moov.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.time.OffsetDateTime;
import java.util.Map;
import java.util.Optional;

/**
 * FullIssuedCard
 * 
 * <p>The full details of an issued card, including PAN and CVV.
 */
public class FullIssuedCard {

    @JsonProperty("issuedCardID")
    private String issuedCardID;

    /**
     * The card brand.
     */
    @JsonProperty("brand")
    private CardBrand brand;


    @JsonProperty("lastFourCardNumber")
    private String lastFourCardNumber;

    /**
     * The expiration date of the card or token.
     */
    @JsonProperty("expiration")
    private CardExpiration expiration;

    /**
     * Unique identifier for the wallet funding the card.
     */
    @JsonProperty("fundingWalletID")
    private String fundingWalletID;

    /**
     * Identifier for the account of the card's authorized user.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("authorizedUserAccountID")
    private Optional<String> authorizedUserAccountID;

    /**
     * An optional descriptive name for the card.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("nickname")
    private Optional<String> nickname;

    /**
     * Free-form key-value pair list. Useful for storing information that is not captured elsewhere.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("metadata")
    private Optional<? extends Map<String, String>> metadata;

    /**
     * Billing address associated with the card.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("billingAddress")
    private Optional<? extends Address> billingAddress;

    /**
     * The `state` represents the operational status of an issued card. A card can only approve incoming
     * authorizations if it is in an active state.
     * 
     * <p>- `active`: The card is operational and can approve authorizations.
     * - `closed`: The card is permanently deactivated and cannot approve authorizations. A card can be
     * closed by request or when it expires.
     */
    @JsonProperty("state")
    private IssuedCardState state;

    /**
     * Specifies the type of spend card to be issued. Presently supports virtual only, providing a digital
     * number without a physical card.
     */
    @JsonProperty("formFactor")
    private IssuedCardFormFactor formFactor;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("controls")
    private Optional<? extends IssuingControls> controls;


    @JsonProperty("createdOn")
    private OffsetDateTime createdOn;


    @JsonProperty("updatedOn")
    private OffsetDateTime updatedOn;

    /**
     * The issued card's Primary Account Number (PAN)
     */
    @JsonProperty("pan")
    private String pan;

    /**
     * The issued card's 3- or 4-digit Card Verification Value (CVV).
     */
    @JsonProperty("cvv")
    private String cvv;

    @JsonCreator
    public FullIssuedCard(
            @JsonProperty("issuedCardID") String issuedCardID,
            @JsonProperty("brand") CardBrand brand,
            @JsonProperty("lastFourCardNumber") String lastFourCardNumber,
            @JsonProperty("expiration") CardExpiration expiration,
            @JsonProperty("fundingWalletID") String fundingWalletID,
            @JsonProperty("authorizedUserAccountID") Optional<String> authorizedUserAccountID,
            @JsonProperty("nickname") Optional<String> nickname,
            @JsonProperty("metadata") Optional<? extends Map<String, String>> metadata,
            @JsonProperty("billingAddress") Optional<? extends Address> billingAddress,
            @JsonProperty("state") IssuedCardState state,
            @JsonProperty("formFactor") IssuedCardFormFactor formFactor,
            @JsonProperty("controls") Optional<? extends IssuingControls> controls,
            @JsonProperty("createdOn") OffsetDateTime createdOn,
            @JsonProperty("updatedOn") OffsetDateTime updatedOn,
            @JsonProperty("pan") String pan,
            @JsonProperty("cvv") String cvv) {
        Utils.checkNotNull(issuedCardID, "issuedCardID");
        Utils.checkNotNull(brand, "brand");
        Utils.checkNotNull(lastFourCardNumber, "lastFourCardNumber");
        Utils.checkNotNull(expiration, "expiration");
        Utils.checkNotNull(fundingWalletID, "fundingWalletID");
        Utils.checkNotNull(authorizedUserAccountID, "authorizedUserAccountID");
        Utils.checkNotNull(nickname, "nickname");
        Utils.checkNotNull(metadata, "metadata");
        Utils.checkNotNull(billingAddress, "billingAddress");
        Utils.checkNotNull(state, "state");
        Utils.checkNotNull(formFactor, "formFactor");
        Utils.checkNotNull(controls, "controls");
        Utils.checkNotNull(createdOn, "createdOn");
        Utils.checkNotNull(updatedOn, "updatedOn");
        Utils.checkNotNull(pan, "pan");
        Utils.checkNotNull(cvv, "cvv");
        this.issuedCardID = issuedCardID;
        this.brand = brand;
        this.lastFourCardNumber = lastFourCardNumber;
        this.expiration = expiration;
        this.fundingWalletID = fundingWalletID;
        this.authorizedUserAccountID = authorizedUserAccountID;
        this.nickname = nickname;
        this.metadata = metadata;
        this.billingAddress = billingAddress;
        this.state = state;
        this.formFactor = formFactor;
        this.controls = controls;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
        this.pan = pan;
        this.cvv = cvv;
    }
    
    public FullIssuedCard(
            String issuedCardID,
            CardBrand brand,
            String lastFourCardNumber,
            CardExpiration expiration,
            String fundingWalletID,
            IssuedCardState state,
            IssuedCardFormFactor formFactor,
            OffsetDateTime createdOn,
            OffsetDateTime updatedOn,
            String pan,
            String cvv) {
        this(issuedCardID, brand, lastFourCardNumber,
            expiration, fundingWalletID, Optional.empty(),
            Optional.empty(), Optional.empty(), Optional.empty(),
            state, formFactor, Optional.empty(),
            createdOn, updatedOn, pan,
            cvv);
    }

    @JsonIgnore
    public String issuedCardID() {
        return issuedCardID;
    }

    /**
     * The card brand.
     */
    @JsonIgnore
    public CardBrand brand() {
        return brand;
    }

    @JsonIgnore
    public String lastFourCardNumber() {
        return lastFourCardNumber;
    }

    /**
     * The expiration date of the card or token.
     */
    @JsonIgnore
    public CardExpiration expiration() {
        return expiration;
    }

    /**
     * Unique identifier for the wallet funding the card.
     */
    @JsonIgnore
    public String fundingWalletID() {
        return fundingWalletID;
    }

    /**
     * Identifier for the account of the card's authorized user.
     */
    @JsonIgnore
    public Optional<String> authorizedUserAccountID() {
        return authorizedUserAccountID;
    }

    /**
     * An optional descriptive name for the card.
     */
    @JsonIgnore
    public Optional<String> nickname() {
        return nickname;
    }

    /**
     * Free-form key-value pair list. Useful for storing information that is not captured elsewhere.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Map<String, String>> metadata() {
        return (Optional<Map<String, String>>) metadata;
    }

    /**
     * Billing address associated with the card.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Address> billingAddress() {
        return (Optional<Address>) billingAddress;
    }

    /**
     * The `state` represents the operational status of an issued card. A card can only approve incoming
     * authorizations if it is in an active state.
     * 
     * <p>- `active`: The card is operational and can approve authorizations.
     * - `closed`: The card is permanently deactivated and cannot approve authorizations. A card can be
     * closed by request or when it expires.
     */
    @JsonIgnore
    public IssuedCardState state() {
        return state;
    }

    /**
     * Specifies the type of spend card to be issued. Presently supports virtual only, providing a digital
     * number without a physical card.
     */
    @JsonIgnore
    public IssuedCardFormFactor formFactor() {
        return formFactor;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<IssuingControls> controls() {
        return (Optional<IssuingControls>) controls;
    }

    @JsonIgnore
    public OffsetDateTime createdOn() {
        return createdOn;
    }

    @JsonIgnore
    public OffsetDateTime updatedOn() {
        return updatedOn;
    }

    /**
     * The issued card's Primary Account Number (PAN)
     */
    @JsonIgnore
    public String pan() {
        return pan;
    }

    /**
     * The issued card's 3- or 4-digit Card Verification Value (CVV).
     */
    @JsonIgnore
    public String cvv() {
        return cvv;
    }

    public static Builder builder() {
        return new Builder();
    }


    public FullIssuedCard withIssuedCardID(String issuedCardID) {
        Utils.checkNotNull(issuedCardID, "issuedCardID");
        this.issuedCardID = issuedCardID;
        return this;
    }

    /**
     * The card brand.
     */
    public FullIssuedCard withBrand(CardBrand brand) {
        Utils.checkNotNull(brand, "brand");
        this.brand = brand;
        return this;
    }

    public FullIssuedCard withLastFourCardNumber(String lastFourCardNumber) {
        Utils.checkNotNull(lastFourCardNumber, "lastFourCardNumber");
        this.lastFourCardNumber = lastFourCardNumber;
        return this;
    }

    /**
     * The expiration date of the card or token.
     */
    public FullIssuedCard withExpiration(CardExpiration expiration) {
        Utils.checkNotNull(expiration, "expiration");
        this.expiration = expiration;
        return this;
    }

    /**
     * Unique identifier for the wallet funding the card.
     */
    public FullIssuedCard withFundingWalletID(String fundingWalletID) {
        Utils.checkNotNull(fundingWalletID, "fundingWalletID");
        this.fundingWalletID = fundingWalletID;
        return this;
    }

    /**
     * Identifier for the account of the card's authorized user.
     */
    public FullIssuedCard withAuthorizedUserAccountID(String authorizedUserAccountID) {
        Utils.checkNotNull(authorizedUserAccountID, "authorizedUserAccountID");
        this.authorizedUserAccountID = Optional.ofNullable(authorizedUserAccountID);
        return this;
    }


    /**
     * Identifier for the account of the card's authorized user.
     */
    public FullIssuedCard withAuthorizedUserAccountID(Optional<String> authorizedUserAccountID) {
        Utils.checkNotNull(authorizedUserAccountID, "authorizedUserAccountID");
        this.authorizedUserAccountID = authorizedUserAccountID;
        return this;
    }

    /**
     * An optional descriptive name for the card.
     */
    public FullIssuedCard withNickname(String nickname) {
        Utils.checkNotNull(nickname, "nickname");
        this.nickname = Optional.ofNullable(nickname);
        return this;
    }


    /**
     * An optional descriptive name for the card.
     */
    public FullIssuedCard withNickname(Optional<String> nickname) {
        Utils.checkNotNull(nickname, "nickname");
        this.nickname = nickname;
        return this;
    }

    /**
     * Free-form key-value pair list. Useful for storing information that is not captured elsewhere.
     */
    public FullIssuedCard withMetadata(Map<String, String> metadata) {
        Utils.checkNotNull(metadata, "metadata");
        this.metadata = Optional.ofNullable(metadata);
        return this;
    }


    /**
     * Free-form key-value pair list. Useful for storing information that is not captured elsewhere.
     */
    public FullIssuedCard withMetadata(Optional<? extends Map<String, String>> metadata) {
        Utils.checkNotNull(metadata, "metadata");
        this.metadata = metadata;
        return this;
    }

    /**
     * Billing address associated with the card.
     */
    public FullIssuedCard withBillingAddress(Address billingAddress) {
        Utils.checkNotNull(billingAddress, "billingAddress");
        this.billingAddress = Optional.ofNullable(billingAddress);
        return this;
    }


    /**
     * Billing address associated with the card.
     */
    public FullIssuedCard withBillingAddress(Optional<? extends Address> billingAddress) {
        Utils.checkNotNull(billingAddress, "billingAddress");
        this.billingAddress = billingAddress;
        return this;
    }

    /**
     * The `state` represents the operational status of an issued card. A card can only approve incoming
     * authorizations if it is in an active state.
     * 
     * <p>- `active`: The card is operational and can approve authorizations.
     * - `closed`: The card is permanently deactivated and cannot approve authorizations. A card can be
     * closed by request or when it expires.
     */
    public FullIssuedCard withState(IssuedCardState state) {
        Utils.checkNotNull(state, "state");
        this.state = state;
        return this;
    }

    /**
     * Specifies the type of spend card to be issued. Presently supports virtual only, providing a digital
     * number without a physical card.
     */
    public FullIssuedCard withFormFactor(IssuedCardFormFactor formFactor) {
        Utils.checkNotNull(formFactor, "formFactor");
        this.formFactor = formFactor;
        return this;
    }

    public FullIssuedCard withControls(IssuingControls controls) {
        Utils.checkNotNull(controls, "controls");
        this.controls = Optional.ofNullable(controls);
        return this;
    }


    public FullIssuedCard withControls(Optional<? extends IssuingControls> controls) {
        Utils.checkNotNull(controls, "controls");
        this.controls = controls;
        return this;
    }

    public FullIssuedCard withCreatedOn(OffsetDateTime createdOn) {
        Utils.checkNotNull(createdOn, "createdOn");
        this.createdOn = createdOn;
        return this;
    }

    public FullIssuedCard withUpdatedOn(OffsetDateTime updatedOn) {
        Utils.checkNotNull(updatedOn, "updatedOn");
        this.updatedOn = updatedOn;
        return this;
    }

    /**
     * The issued card's Primary Account Number (PAN)
     */
    public FullIssuedCard withPan(String pan) {
        Utils.checkNotNull(pan, "pan");
        this.pan = pan;
        return this;
    }

    /**
     * The issued card's 3- or 4-digit Card Verification Value (CVV).
     */
    public FullIssuedCard withCvv(String cvv) {
        Utils.checkNotNull(cvv, "cvv");
        this.cvv = cvv;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        FullIssuedCard other = (FullIssuedCard) o;
        return 
            Utils.enhancedDeepEquals(this.issuedCardID, other.issuedCardID) &&
            Utils.enhancedDeepEquals(this.brand, other.brand) &&
            Utils.enhancedDeepEquals(this.lastFourCardNumber, other.lastFourCardNumber) &&
            Utils.enhancedDeepEquals(this.expiration, other.expiration) &&
            Utils.enhancedDeepEquals(this.fundingWalletID, other.fundingWalletID) &&
            Utils.enhancedDeepEquals(this.authorizedUserAccountID, other.authorizedUserAccountID) &&
            Utils.enhancedDeepEquals(this.nickname, other.nickname) &&
            Utils.enhancedDeepEquals(this.metadata, other.metadata) &&
            Utils.enhancedDeepEquals(this.billingAddress, other.billingAddress) &&
            Utils.enhancedDeepEquals(this.state, other.state) &&
            Utils.enhancedDeepEquals(this.formFactor, other.formFactor) &&
            Utils.enhancedDeepEquals(this.controls, other.controls) &&
            Utils.enhancedDeepEquals(this.createdOn, other.createdOn) &&
            Utils.enhancedDeepEquals(this.updatedOn, other.updatedOn) &&
            Utils.enhancedDeepEquals(this.pan, other.pan) &&
            Utils.enhancedDeepEquals(this.cvv, other.cvv);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            issuedCardID, brand, lastFourCardNumber,
            expiration, fundingWalletID, authorizedUserAccountID,
            nickname, metadata, billingAddress,
            state, formFactor, controls,
            createdOn, updatedOn, pan,
            cvv);
    }
    
    @Override
    public String toString() {
        return Utils.toString(FullIssuedCard.class,
                "issuedCardID", issuedCardID,
                "brand", brand,
                "lastFourCardNumber", lastFourCardNumber,
                "expiration", expiration,
                "fundingWalletID", fundingWalletID,
                "authorizedUserAccountID", authorizedUserAccountID,
                "nickname", nickname,
                "metadata", metadata,
                "billingAddress", billingAddress,
                "state", state,
                "formFactor", formFactor,
                "controls", controls,
                "createdOn", createdOn,
                "updatedOn", updatedOn,
                "pan", pan,
                "cvv", cvv);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String issuedCardID;

        private CardBrand brand;

        private String lastFourCardNumber;

        private CardExpiration expiration;

        private String fundingWalletID;

        private Optional<String> authorizedUserAccountID = Optional.empty();

        private Optional<String> nickname = Optional.empty();

        private Optional<? extends Map<String, String>> metadata = Optional.empty();

        private Optional<? extends Address> billingAddress = Optional.empty();

        private IssuedCardState state;

        private IssuedCardFormFactor formFactor;

        private Optional<? extends IssuingControls> controls = Optional.empty();

        private OffsetDateTime createdOn;

        private OffsetDateTime updatedOn;

        private String pan;

        private String cvv;

        private Builder() {
          // force use of static builder() method
        }


        public Builder issuedCardID(String issuedCardID) {
            Utils.checkNotNull(issuedCardID, "issuedCardID");
            this.issuedCardID = issuedCardID;
            return this;
        }


        /**
         * The card brand.
         */
        public Builder brand(CardBrand brand) {
            Utils.checkNotNull(brand, "brand");
            this.brand = brand;
            return this;
        }


        public Builder lastFourCardNumber(String lastFourCardNumber) {
            Utils.checkNotNull(lastFourCardNumber, "lastFourCardNumber");
            this.lastFourCardNumber = lastFourCardNumber;
            return this;
        }


        /**
         * The expiration date of the card or token.
         */
        public Builder expiration(CardExpiration expiration) {
            Utils.checkNotNull(expiration, "expiration");
            this.expiration = expiration;
            return this;
        }


        /**
         * Unique identifier for the wallet funding the card.
         */
        public Builder fundingWalletID(String fundingWalletID) {
            Utils.checkNotNull(fundingWalletID, "fundingWalletID");
            this.fundingWalletID = fundingWalletID;
            return this;
        }


        /**
         * Identifier for the account of the card's authorized user.
         */
        public Builder authorizedUserAccountID(String authorizedUserAccountID) {
            Utils.checkNotNull(authorizedUserAccountID, "authorizedUserAccountID");
            this.authorizedUserAccountID = Optional.ofNullable(authorizedUserAccountID);
            return this;
        }

        /**
         * Identifier for the account of the card's authorized user.
         */
        public Builder authorizedUserAccountID(Optional<String> authorizedUserAccountID) {
            Utils.checkNotNull(authorizedUserAccountID, "authorizedUserAccountID");
            this.authorizedUserAccountID = authorizedUserAccountID;
            return this;
        }


        /**
         * An optional descriptive name for the card.
         */
        public Builder nickname(String nickname) {
            Utils.checkNotNull(nickname, "nickname");
            this.nickname = Optional.ofNullable(nickname);
            return this;
        }

        /**
         * An optional descriptive name for the card.
         */
        public Builder nickname(Optional<String> nickname) {
            Utils.checkNotNull(nickname, "nickname");
            this.nickname = nickname;
            return this;
        }


        /**
         * Free-form key-value pair list. Useful for storing information that is not captured elsewhere.
         */
        public Builder metadata(Map<String, String> metadata) {
            Utils.checkNotNull(metadata, "metadata");
            this.metadata = Optional.ofNullable(metadata);
            return this;
        }

        /**
         * Free-form key-value pair list. Useful for storing information that is not captured elsewhere.
         */
        public Builder metadata(Optional<? extends Map<String, String>> metadata) {
            Utils.checkNotNull(metadata, "metadata");
            this.metadata = metadata;
            return this;
        }


        /**
         * Billing address associated with the card.
         */
        public Builder billingAddress(Address billingAddress) {
            Utils.checkNotNull(billingAddress, "billingAddress");
            this.billingAddress = Optional.ofNullable(billingAddress);
            return this;
        }

        /**
         * Billing address associated with the card.
         */
        public Builder billingAddress(Optional<? extends Address> billingAddress) {
            Utils.checkNotNull(billingAddress, "billingAddress");
            this.billingAddress = billingAddress;
            return this;
        }


        /**
         * The `state` represents the operational status of an issued card. A card can only approve incoming
         * authorizations if it is in an active state.
         * 
         * <p>- `active`: The card is operational and can approve authorizations.
         * - `closed`: The card is permanently deactivated and cannot approve authorizations. A card can be
         * closed by request or when it expires.
         */
        public Builder state(IssuedCardState state) {
            Utils.checkNotNull(state, "state");
            this.state = state;
            return this;
        }


        /**
         * Specifies the type of spend card to be issued. Presently supports virtual only, providing a digital
         * number without a physical card.
         */
        public Builder formFactor(IssuedCardFormFactor formFactor) {
            Utils.checkNotNull(formFactor, "formFactor");
            this.formFactor = formFactor;
            return this;
        }


        public Builder controls(IssuingControls controls) {
            Utils.checkNotNull(controls, "controls");
            this.controls = Optional.ofNullable(controls);
            return this;
        }

        public Builder controls(Optional<? extends IssuingControls> controls) {
            Utils.checkNotNull(controls, "controls");
            this.controls = controls;
            return this;
        }


        public Builder createdOn(OffsetDateTime createdOn) {
            Utils.checkNotNull(createdOn, "createdOn");
            this.createdOn = createdOn;
            return this;
        }


        public Builder updatedOn(OffsetDateTime updatedOn) {
            Utils.checkNotNull(updatedOn, "updatedOn");
            this.updatedOn = updatedOn;
            return this;
        }


        /**
         * The issued card's Primary Account Number (PAN)
         */
        public Builder pan(String pan) {
            Utils.checkNotNull(pan, "pan");
            this.pan = pan;
            return this;
        }


        /**
         * The issued card's 3- or 4-digit Card Verification Value (CVV).
         */
        public Builder cvv(String cvv) {
            Utils.checkNotNull(cvv, "cvv");
            this.cvv = cvv;
            return this;
        }

        public FullIssuedCard build() {

            return new FullIssuedCard(
                issuedCardID, brand, lastFourCardNumber,
                expiration, fundingWalletID, authorizedUserAccountID,
                nickname, metadata, billingAddress,
                state, formFactor, controls,
                createdOn, updatedOn, pan,
                cvv);
        }

    }
}
