/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.moov.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.moov.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;


public class InvoiceTransferPayment {

    @JsonProperty("transferID")
    private String transferID;

    @JsonCreator
    public InvoiceTransferPayment(
            @JsonProperty("transferID") String transferID) {
        Utils.checkNotNull(transferID, "transferID");
        this.transferID = transferID;
    }

    @JsonIgnore
    public String transferID() {
        return transferID;
    }

    public static Builder builder() {
        return new Builder();
    }


    public InvoiceTransferPayment withTransferID(String transferID) {
        Utils.checkNotNull(transferID, "transferID");
        this.transferID = transferID;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InvoiceTransferPayment other = (InvoiceTransferPayment) o;
        return 
            Utils.enhancedDeepEquals(this.transferID, other.transferID);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            transferID);
    }
    
    @Override
    public String toString() {
        return Utils.toString(InvoiceTransferPayment.class,
                "transferID", transferID);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String transferID;

        private Builder() {
          // force use of static builder() method
        }


        public Builder transferID(String transferID) {
            Utils.checkNotNull(transferID, "transferID");
            this.transferID = transferID;
            return this;
        }

        public InvoiceTransferPayment build() {

            return new InvoiceTransferPayment(
                transferID);
        }

    }
}
