/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.moov.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.moov.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.time.OffsetDateTime;


public class Residual {
    /**
     * Unique identifier for this residual payment calculation.
     */
    @JsonProperty("residualID")
    private String residualID;

    /**
     * The partner account ID this residual belongs to.
     */
    @JsonProperty("partnerAccountID")
    private String partnerAccountID;

    /**
     * Start date and time of the residual calculation period.
     */
    @JsonProperty("periodStart")
    private OffsetDateTime periodStart;

    /**
     * End date and time of the residual calculation period.
     */
    @JsonProperty("periodEnd")
    private OffsetDateTime periodEnd;

    /**
     * Total amount of merchant fees collected during the period. This represents the partner's revenue
     * from merchant fees.
     */
    @JsonProperty("merchantFees")
    private AmountDecimal merchantFees;

    /**
     * Partner's total cost (buy rate) during the period.
     */
    @JsonProperty("partnerCost")
    private AmountDecimal partnerCost;

    /**
     * Net income calculated as merchant fee revenue minus partner costs.
     */
    @JsonProperty("netIncome")
    private AmountDecimal netIncome;

    /**
     * The revenue share percentage the partner receives, expressed as a decimal string (e.g., "25.00" for
     * 25%).
     */
    @JsonProperty("revenueShare")
    private String revenueShare;

    /**
     * The amount the partner receives as their share of the net income (netIncome × revenueShare).
     */
    @JsonProperty("residualAmount")
    private AmountDecimal residualAmount;

    /**
     * Timestamp when the residual was created.
     */
    @JsonProperty("createdOn")
    private OffsetDateTime createdOn;

    /**
     * Timestamp when the residual was last updated.
     */
    @JsonProperty("updatedOn")
    private OffsetDateTime updatedOn;

    @JsonCreator
    public Residual(
            @JsonProperty("residualID") String residualID,
            @JsonProperty("partnerAccountID") String partnerAccountID,
            @JsonProperty("periodStart") OffsetDateTime periodStart,
            @JsonProperty("periodEnd") OffsetDateTime periodEnd,
            @JsonProperty("merchantFees") AmountDecimal merchantFees,
            @JsonProperty("partnerCost") AmountDecimal partnerCost,
            @JsonProperty("netIncome") AmountDecimal netIncome,
            @JsonProperty("revenueShare") String revenueShare,
            @JsonProperty("residualAmount") AmountDecimal residualAmount,
            @JsonProperty("createdOn") OffsetDateTime createdOn,
            @JsonProperty("updatedOn") OffsetDateTime updatedOn) {
        Utils.checkNotNull(residualID, "residualID");
        Utils.checkNotNull(partnerAccountID, "partnerAccountID");
        Utils.checkNotNull(periodStart, "periodStart");
        Utils.checkNotNull(periodEnd, "periodEnd");
        Utils.checkNotNull(merchantFees, "merchantFees");
        Utils.checkNotNull(partnerCost, "partnerCost");
        Utils.checkNotNull(netIncome, "netIncome");
        Utils.checkNotNull(revenueShare, "revenueShare");
        Utils.checkNotNull(residualAmount, "residualAmount");
        Utils.checkNotNull(createdOn, "createdOn");
        Utils.checkNotNull(updatedOn, "updatedOn");
        this.residualID = residualID;
        this.partnerAccountID = partnerAccountID;
        this.periodStart = periodStart;
        this.periodEnd = periodEnd;
        this.merchantFees = merchantFees;
        this.partnerCost = partnerCost;
        this.netIncome = netIncome;
        this.revenueShare = revenueShare;
        this.residualAmount = residualAmount;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    /**
     * Unique identifier for this residual payment calculation.
     */
    @JsonIgnore
    public String residualID() {
        return residualID;
    }

    /**
     * The partner account ID this residual belongs to.
     */
    @JsonIgnore
    public String partnerAccountID() {
        return partnerAccountID;
    }

    /**
     * Start date and time of the residual calculation period.
     */
    @JsonIgnore
    public OffsetDateTime periodStart() {
        return periodStart;
    }

    /**
     * End date and time of the residual calculation period.
     */
    @JsonIgnore
    public OffsetDateTime periodEnd() {
        return periodEnd;
    }

    /**
     * Total amount of merchant fees collected during the period. This represents the partner's revenue
     * from merchant fees.
     */
    @JsonIgnore
    public AmountDecimal merchantFees() {
        return merchantFees;
    }

    /**
     * Partner's total cost (buy rate) during the period.
     */
    @JsonIgnore
    public AmountDecimal partnerCost() {
        return partnerCost;
    }

    /**
     * Net income calculated as merchant fee revenue minus partner costs.
     */
    @JsonIgnore
    public AmountDecimal netIncome() {
        return netIncome;
    }

    /**
     * The revenue share percentage the partner receives, expressed as a decimal string (e.g., "25.00" for
     * 25%).
     */
    @JsonIgnore
    public String revenueShare() {
        return revenueShare;
    }

    /**
     * The amount the partner receives as their share of the net income (netIncome × revenueShare).
     */
    @JsonIgnore
    public AmountDecimal residualAmount() {
        return residualAmount;
    }

    /**
     * Timestamp when the residual was created.
     */
    @JsonIgnore
    public OffsetDateTime createdOn() {
        return createdOn;
    }

    /**
     * Timestamp when the residual was last updated.
     */
    @JsonIgnore
    public OffsetDateTime updatedOn() {
        return updatedOn;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Unique identifier for this residual payment calculation.
     */
    public Residual withResidualID(String residualID) {
        Utils.checkNotNull(residualID, "residualID");
        this.residualID = residualID;
        return this;
    }

    /**
     * The partner account ID this residual belongs to.
     */
    public Residual withPartnerAccountID(String partnerAccountID) {
        Utils.checkNotNull(partnerAccountID, "partnerAccountID");
        this.partnerAccountID = partnerAccountID;
        return this;
    }

    /**
     * Start date and time of the residual calculation period.
     */
    public Residual withPeriodStart(OffsetDateTime periodStart) {
        Utils.checkNotNull(periodStart, "periodStart");
        this.periodStart = periodStart;
        return this;
    }

    /**
     * End date and time of the residual calculation period.
     */
    public Residual withPeriodEnd(OffsetDateTime periodEnd) {
        Utils.checkNotNull(periodEnd, "periodEnd");
        this.periodEnd = periodEnd;
        return this;
    }

    /**
     * Total amount of merchant fees collected during the period. This represents the partner's revenue
     * from merchant fees.
     */
    public Residual withMerchantFees(AmountDecimal merchantFees) {
        Utils.checkNotNull(merchantFees, "merchantFees");
        this.merchantFees = merchantFees;
        return this;
    }

    /**
     * Partner's total cost (buy rate) during the period.
     */
    public Residual withPartnerCost(AmountDecimal partnerCost) {
        Utils.checkNotNull(partnerCost, "partnerCost");
        this.partnerCost = partnerCost;
        return this;
    }

    /**
     * Net income calculated as merchant fee revenue minus partner costs.
     */
    public Residual withNetIncome(AmountDecimal netIncome) {
        Utils.checkNotNull(netIncome, "netIncome");
        this.netIncome = netIncome;
        return this;
    }

    /**
     * The revenue share percentage the partner receives, expressed as a decimal string (e.g., "25.00" for
     * 25%).
     */
    public Residual withRevenueShare(String revenueShare) {
        Utils.checkNotNull(revenueShare, "revenueShare");
        this.revenueShare = revenueShare;
        return this;
    }

    /**
     * The amount the partner receives as their share of the net income (netIncome × revenueShare).
     */
    public Residual withResidualAmount(AmountDecimal residualAmount) {
        Utils.checkNotNull(residualAmount, "residualAmount");
        this.residualAmount = residualAmount;
        return this;
    }

    /**
     * Timestamp when the residual was created.
     */
    public Residual withCreatedOn(OffsetDateTime createdOn) {
        Utils.checkNotNull(createdOn, "createdOn");
        this.createdOn = createdOn;
        return this;
    }

    /**
     * Timestamp when the residual was last updated.
     */
    public Residual withUpdatedOn(OffsetDateTime updatedOn) {
        Utils.checkNotNull(updatedOn, "updatedOn");
        this.updatedOn = updatedOn;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Residual other = (Residual) o;
        return 
            Utils.enhancedDeepEquals(this.residualID, other.residualID) &&
            Utils.enhancedDeepEquals(this.partnerAccountID, other.partnerAccountID) &&
            Utils.enhancedDeepEquals(this.periodStart, other.periodStart) &&
            Utils.enhancedDeepEquals(this.periodEnd, other.periodEnd) &&
            Utils.enhancedDeepEquals(this.merchantFees, other.merchantFees) &&
            Utils.enhancedDeepEquals(this.partnerCost, other.partnerCost) &&
            Utils.enhancedDeepEquals(this.netIncome, other.netIncome) &&
            Utils.enhancedDeepEquals(this.revenueShare, other.revenueShare) &&
            Utils.enhancedDeepEquals(this.residualAmount, other.residualAmount) &&
            Utils.enhancedDeepEquals(this.createdOn, other.createdOn) &&
            Utils.enhancedDeepEquals(this.updatedOn, other.updatedOn);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            residualID, partnerAccountID, periodStart,
            periodEnd, merchantFees, partnerCost,
            netIncome, revenueShare, residualAmount,
            createdOn, updatedOn);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Residual.class,
                "residualID", residualID,
                "partnerAccountID", partnerAccountID,
                "periodStart", periodStart,
                "periodEnd", periodEnd,
                "merchantFees", merchantFees,
                "partnerCost", partnerCost,
                "netIncome", netIncome,
                "revenueShare", revenueShare,
                "residualAmount", residualAmount,
                "createdOn", createdOn,
                "updatedOn", updatedOn);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String residualID;

        private String partnerAccountID;

        private OffsetDateTime periodStart;

        private OffsetDateTime periodEnd;

        private AmountDecimal merchantFees;

        private AmountDecimal partnerCost;

        private AmountDecimal netIncome;

        private String revenueShare;

        private AmountDecimal residualAmount;

        private OffsetDateTime createdOn;

        private OffsetDateTime updatedOn;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Unique identifier for this residual payment calculation.
         */
        public Builder residualID(String residualID) {
            Utils.checkNotNull(residualID, "residualID");
            this.residualID = residualID;
            return this;
        }


        /**
         * The partner account ID this residual belongs to.
         */
        public Builder partnerAccountID(String partnerAccountID) {
            Utils.checkNotNull(partnerAccountID, "partnerAccountID");
            this.partnerAccountID = partnerAccountID;
            return this;
        }


        /**
         * Start date and time of the residual calculation period.
         */
        public Builder periodStart(OffsetDateTime periodStart) {
            Utils.checkNotNull(periodStart, "periodStart");
            this.periodStart = periodStart;
            return this;
        }


        /**
         * End date and time of the residual calculation period.
         */
        public Builder periodEnd(OffsetDateTime periodEnd) {
            Utils.checkNotNull(periodEnd, "periodEnd");
            this.periodEnd = periodEnd;
            return this;
        }


        /**
         * Total amount of merchant fees collected during the period. This represents the partner's revenue
         * from merchant fees.
         */
        public Builder merchantFees(AmountDecimal merchantFees) {
            Utils.checkNotNull(merchantFees, "merchantFees");
            this.merchantFees = merchantFees;
            return this;
        }


        /**
         * Partner's total cost (buy rate) during the period.
         */
        public Builder partnerCost(AmountDecimal partnerCost) {
            Utils.checkNotNull(partnerCost, "partnerCost");
            this.partnerCost = partnerCost;
            return this;
        }


        /**
         * Net income calculated as merchant fee revenue minus partner costs.
         */
        public Builder netIncome(AmountDecimal netIncome) {
            Utils.checkNotNull(netIncome, "netIncome");
            this.netIncome = netIncome;
            return this;
        }


        /**
         * The revenue share percentage the partner receives, expressed as a decimal string (e.g., "25.00" for
         * 25%).
         */
        public Builder revenueShare(String revenueShare) {
            Utils.checkNotNull(revenueShare, "revenueShare");
            this.revenueShare = revenueShare;
            return this;
        }


        /**
         * The amount the partner receives as their share of the net income (netIncome × revenueShare).
         */
        public Builder residualAmount(AmountDecimal residualAmount) {
            Utils.checkNotNull(residualAmount, "residualAmount");
            this.residualAmount = residualAmount;
            return this;
        }


        /**
         * Timestamp when the residual was created.
         */
        public Builder createdOn(OffsetDateTime createdOn) {
            Utils.checkNotNull(createdOn, "createdOn");
            this.createdOn = createdOn;
            return this;
        }


        /**
         * Timestamp when the residual was last updated.
         */
        public Builder updatedOn(OffsetDateTime updatedOn) {
            Utils.checkNotNull(updatedOn, "updatedOn");
            this.updatedOn = updatedOn;
            return this;
        }

        public Residual build() {

            return new Residual(
                residualID, partnerAccountID, periodStart,
                periodEnd, merchantFees, partnerCost,
                netIncome, revenueShare, residualAmount,
                createdOn, updatedOn);
        }

    }
}
