/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.moov.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.moov.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;


public class TransferEventRefundDetails {
    /**
     * A unique identifier for a Moov resource. Supports UUID format (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
     * or typed format with base32-encoded UUID and type suffix (e.g., kuoaydiojf7uszaokc2ggnaaaa_xfer).
     */
    @JsonProperty("refundID")
    private String refundID;

    /**
     * A unique identifier for a Moov resource. Supports UUID format (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
     * or typed format with base32-encoded UUID and type suffix (e.g., kuoaydiojf7uszaokc2ggnaaaa_xfer).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("captureID")
    private Optional<String> captureID;


    @JsonProperty("status")
    private RefundStatus status;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("failureCode")
    private Optional<? extends CardTransactionFailureCode> failureCode;

    @JsonCreator
    public TransferEventRefundDetails(
            @JsonProperty("refundID") String refundID,
            @JsonProperty("captureID") Optional<String> captureID,
            @JsonProperty("status") RefundStatus status,
            @JsonProperty("failureCode") Optional<? extends CardTransactionFailureCode> failureCode) {
        Utils.checkNotNull(refundID, "refundID");
        Utils.checkNotNull(captureID, "captureID");
        Utils.checkNotNull(status, "status");
        Utils.checkNotNull(failureCode, "failureCode");
        this.refundID = refundID;
        this.captureID = captureID;
        this.status = status;
        this.failureCode = failureCode;
    }
    
    public TransferEventRefundDetails(
            String refundID,
            RefundStatus status) {
        this(refundID, Optional.empty(), status,
            Optional.empty());
    }

    /**
     * A unique identifier for a Moov resource. Supports UUID format (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
     * or typed format with base32-encoded UUID and type suffix (e.g., kuoaydiojf7uszaokc2ggnaaaa_xfer).
     */
    @JsonIgnore
    public String refundID() {
        return refundID;
    }

    /**
     * A unique identifier for a Moov resource. Supports UUID format (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
     * or typed format with base32-encoded UUID and type suffix (e.g., kuoaydiojf7uszaokc2ggnaaaa_xfer).
     */
    @JsonIgnore
    public Optional<String> captureID() {
        return captureID;
    }

    @JsonIgnore
    public RefundStatus status() {
        return status;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<CardTransactionFailureCode> failureCode() {
        return (Optional<CardTransactionFailureCode>) failureCode;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * A unique identifier for a Moov resource. Supports UUID format (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
     * or typed format with base32-encoded UUID and type suffix (e.g., kuoaydiojf7uszaokc2ggnaaaa_xfer).
     */
    public TransferEventRefundDetails withRefundID(String refundID) {
        Utils.checkNotNull(refundID, "refundID");
        this.refundID = refundID;
        return this;
    }

    /**
     * A unique identifier for a Moov resource. Supports UUID format (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
     * or typed format with base32-encoded UUID and type suffix (e.g., kuoaydiojf7uszaokc2ggnaaaa_xfer).
     */
    public TransferEventRefundDetails withCaptureID(String captureID) {
        Utils.checkNotNull(captureID, "captureID");
        this.captureID = Optional.ofNullable(captureID);
        return this;
    }


    /**
     * A unique identifier for a Moov resource. Supports UUID format (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
     * or typed format with base32-encoded UUID and type suffix (e.g., kuoaydiojf7uszaokc2ggnaaaa_xfer).
     */
    public TransferEventRefundDetails withCaptureID(Optional<String> captureID) {
        Utils.checkNotNull(captureID, "captureID");
        this.captureID = captureID;
        return this;
    }

    public TransferEventRefundDetails withStatus(RefundStatus status) {
        Utils.checkNotNull(status, "status");
        this.status = status;
        return this;
    }

    public TransferEventRefundDetails withFailureCode(CardTransactionFailureCode failureCode) {
        Utils.checkNotNull(failureCode, "failureCode");
        this.failureCode = Optional.ofNullable(failureCode);
        return this;
    }


    public TransferEventRefundDetails withFailureCode(Optional<? extends CardTransactionFailureCode> failureCode) {
        Utils.checkNotNull(failureCode, "failureCode");
        this.failureCode = failureCode;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TransferEventRefundDetails other = (TransferEventRefundDetails) o;
        return 
            Utils.enhancedDeepEquals(this.refundID, other.refundID) &&
            Utils.enhancedDeepEquals(this.captureID, other.captureID) &&
            Utils.enhancedDeepEquals(this.status, other.status) &&
            Utils.enhancedDeepEquals(this.failureCode, other.failureCode);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            refundID, captureID, status,
            failureCode);
    }
    
    @Override
    public String toString() {
        return Utils.toString(TransferEventRefundDetails.class,
                "refundID", refundID,
                "captureID", captureID,
                "status", status,
                "failureCode", failureCode);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String refundID;

        private Optional<String> captureID = Optional.empty();

        private RefundStatus status;

        private Optional<? extends CardTransactionFailureCode> failureCode = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * A unique identifier for a Moov resource. Supports UUID format (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
         * or typed format with base32-encoded UUID and type suffix (e.g., kuoaydiojf7uszaokc2ggnaaaa_xfer).
         */
        public Builder refundID(String refundID) {
            Utils.checkNotNull(refundID, "refundID");
            this.refundID = refundID;
            return this;
        }


        /**
         * A unique identifier for a Moov resource. Supports UUID format (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
         * or typed format with base32-encoded UUID and type suffix (e.g., kuoaydiojf7uszaokc2ggnaaaa_xfer).
         */
        public Builder captureID(String captureID) {
            Utils.checkNotNull(captureID, "captureID");
            this.captureID = Optional.ofNullable(captureID);
            return this;
        }

        /**
         * A unique identifier for a Moov resource. Supports UUID format (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
         * or typed format with base32-encoded UUID and type suffix (e.g., kuoaydiojf7uszaokc2ggnaaaa_xfer).
         */
        public Builder captureID(Optional<String> captureID) {
            Utils.checkNotNull(captureID, "captureID");
            this.captureID = captureID;
            return this;
        }


        public Builder status(RefundStatus status) {
            Utils.checkNotNull(status, "status");
            this.status = status;
            return this;
        }


        public Builder failureCode(CardTransactionFailureCode failureCode) {
            Utils.checkNotNull(failureCode, "failureCode");
            this.failureCode = Optional.ofNullable(failureCode);
            return this;
        }

        public Builder failureCode(Optional<? extends CardTransactionFailureCode> failureCode) {
            Utils.checkNotNull(failureCode, "failureCode");
            this.failureCode = failureCode;
            return this;
        }

        public TransferEventRefundDetails build() {

            return new TransferEventRefundDetails(
                refundID, captureID, status,
                failureCode);
        }

    }
}
