/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.moov.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.moov.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Transfer
 * 
 * <p>Details of a Transfer.
 */
public class Transfer {

    @JsonProperty("transferID")
    private String transferID;

    /**
     * The rail and direction used to move funds for a transfer.
     */
    @JsonProperty("transferType")
    private TransferType transferType;


    @JsonProperty("createdOn")
    private OffsetDateTime createdOn;


    @JsonProperty("source")
    private TransferSource source;


    @JsonProperty("destination")
    private TransferDestination destination;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("completedOn")
    private Optional<OffsetDateTime> completedOn;

    /**
     * Status of a transfer.
     */
    @JsonProperty("status")
    private TransferStatus status;

    /**
     * Reason for a transfer's failure.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("failureReason")
    private Optional<? extends TransferFailureReason> failureReason;


    @JsonProperty("amount")
    private AmountDecimal amount;

    /**
     * An optional description of the transfer that is used on receipts and for your own internal use.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    private Optional<String> description;

    /**
     * Free-form key-value pair list. Useful for storing information that is not captured elsewhere.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("metadata")
    private Optional<? extends Map<String, String>> metadata;

    /**
     * Total or markup fee.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("facilitatorFee")
    private Optional<? extends FacilitatorFee> facilitatorFee;

    /**
     * Fees charged to your platform account for transfers.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("moovFee")
    private Optional<? extends AmountDecimal> moovFee;

    /**
     * Processing and pass-through costs that add up to the moovFee.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("moovFeeDetails")
    private Optional<? extends MoovFeeDetails> moovFeeDetails;

    /**
     * Fees charged to accounts involved in the transfer.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("moovFees")
    private Optional<? extends List<MoovFee>> moovFees;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("groupID")
    private Optional<String> groupID;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("refundedAmount")
    private Optional<? extends AmountDecimal> refundedAmount;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("disputedAmount")
    private Optional<? extends AmountDecimal> disputedAmount;

    /**
     * ID of the sweep that created this transfer.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("sweepID")
    private Optional<String> sweepID;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("scheduleID")
    private Optional<String> scheduleID;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("occurrenceID")
    private Optional<String> occurrenceID;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("paymentLinkCode")
    private Optional<String> paymentLinkCode;

    /**
     * Optional alias from a foreign/external system which can be used to reference this resource.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("foreignID")
    private Optional<String> foreignID;

    /**
     * An optional collection of line items for a transfer.
     * When line items are provided, their total plus tax must equal the transfer amount.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("lineItems")
    private Optional<? extends TransferLineItems> lineItems;

    /**
     * ID of the invoice that the transfer is associated with.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("invoiceID")
    private Optional<String> invoiceID;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("amountDetails")
    private Optional<? extends TransferAmountDetails> amountDetails;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("authorization")
    private Optional<? extends TransferAuthorization> authorization;


    @JsonProperty("options")
    private TransferRailOptions options;


    @JsonProperty("processingDetails")
    private TransferProcessingDetails processingDetails;

    @JsonCreator
    public Transfer(
            @JsonProperty("transferID") String transferID,
            @JsonProperty("transferType") TransferType transferType,
            @JsonProperty("createdOn") OffsetDateTime createdOn,
            @JsonProperty("source") TransferSource source,
            @JsonProperty("destination") TransferDestination destination,
            @JsonProperty("completedOn") Optional<OffsetDateTime> completedOn,
            @JsonProperty("status") TransferStatus status,
            @JsonProperty("failureReason") Optional<? extends TransferFailureReason> failureReason,
            @JsonProperty("amount") AmountDecimal amount,
            @JsonProperty("description") Optional<String> description,
            @JsonProperty("metadata") Optional<? extends Map<String, String>> metadata,
            @JsonProperty("facilitatorFee") Optional<? extends FacilitatorFee> facilitatorFee,
            @JsonProperty("moovFee") Optional<? extends AmountDecimal> moovFee,
            @JsonProperty("moovFeeDetails") Optional<? extends MoovFeeDetails> moovFeeDetails,
            @JsonProperty("moovFees") Optional<? extends List<MoovFee>> moovFees,
            @JsonProperty("groupID") Optional<String> groupID,
            @JsonProperty("refundedAmount") Optional<? extends AmountDecimal> refundedAmount,
            @JsonProperty("disputedAmount") Optional<? extends AmountDecimal> disputedAmount,
            @JsonProperty("sweepID") Optional<String> sweepID,
            @JsonProperty("scheduleID") Optional<String> scheduleID,
            @JsonProperty("occurrenceID") Optional<String> occurrenceID,
            @JsonProperty("paymentLinkCode") Optional<String> paymentLinkCode,
            @JsonProperty("foreignID") Optional<String> foreignID,
            @JsonProperty("lineItems") Optional<? extends TransferLineItems> lineItems,
            @JsonProperty("invoiceID") Optional<String> invoiceID,
            @JsonProperty("amountDetails") Optional<? extends TransferAmountDetails> amountDetails,
            @JsonProperty("authorization") Optional<? extends TransferAuthorization> authorization,
            @JsonProperty("options") TransferRailOptions options,
            @JsonProperty("processingDetails") TransferProcessingDetails processingDetails) {
        Utils.checkNotNull(transferID, "transferID");
        Utils.checkNotNull(transferType, "transferType");
        Utils.checkNotNull(createdOn, "createdOn");
        Utils.checkNotNull(source, "source");
        Utils.checkNotNull(destination, "destination");
        Utils.checkNotNull(completedOn, "completedOn");
        Utils.checkNotNull(status, "status");
        Utils.checkNotNull(failureReason, "failureReason");
        Utils.checkNotNull(amount, "amount");
        Utils.checkNotNull(description, "description");
        Utils.checkNotNull(metadata, "metadata");
        Utils.checkNotNull(facilitatorFee, "facilitatorFee");
        Utils.checkNotNull(moovFee, "moovFee");
        Utils.checkNotNull(moovFeeDetails, "moovFeeDetails");
        Utils.checkNotNull(moovFees, "moovFees");
        Utils.checkNotNull(groupID, "groupID");
        Utils.checkNotNull(refundedAmount, "refundedAmount");
        Utils.checkNotNull(disputedAmount, "disputedAmount");
        Utils.checkNotNull(sweepID, "sweepID");
        Utils.checkNotNull(scheduleID, "scheduleID");
        Utils.checkNotNull(occurrenceID, "occurrenceID");
        Utils.checkNotNull(paymentLinkCode, "paymentLinkCode");
        Utils.checkNotNull(foreignID, "foreignID");
        Utils.checkNotNull(lineItems, "lineItems");
        Utils.checkNotNull(invoiceID, "invoiceID");
        Utils.checkNotNull(amountDetails, "amountDetails");
        Utils.checkNotNull(authorization, "authorization");
        Utils.checkNotNull(options, "options");
        Utils.checkNotNull(processingDetails, "processingDetails");
        this.transferID = transferID;
        this.transferType = transferType;
        this.createdOn = createdOn;
        this.source = source;
        this.destination = destination;
        this.completedOn = completedOn;
        this.status = status;
        this.failureReason = failureReason;
        this.amount = amount;
        this.description = description;
        this.metadata = metadata;
        this.facilitatorFee = facilitatorFee;
        this.moovFee = moovFee;
        this.moovFeeDetails = moovFeeDetails;
        this.moovFees = moovFees;
        this.groupID = groupID;
        this.refundedAmount = refundedAmount;
        this.disputedAmount = disputedAmount;
        this.sweepID = sweepID;
        this.scheduleID = scheduleID;
        this.occurrenceID = occurrenceID;
        this.paymentLinkCode = paymentLinkCode;
        this.foreignID = foreignID;
        this.lineItems = lineItems;
        this.invoiceID = invoiceID;
        this.amountDetails = amountDetails;
        this.authorization = authorization;
        this.options = options;
        this.processingDetails = processingDetails;
    }
    
    public Transfer(
            String transferID,
            TransferType transferType,
            OffsetDateTime createdOn,
            TransferSource source,
            TransferDestination destination,
            TransferStatus status,
            AmountDecimal amount,
            TransferRailOptions options,
            TransferProcessingDetails processingDetails) {
        this(transferID, transferType, createdOn,
            source, destination, Optional.empty(),
            status, Optional.empty(), amount,
            Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty(), Optional.empty(),
            options, processingDetails);
    }

    @JsonIgnore
    public String transferID() {
        return transferID;
    }

    /**
     * The rail and direction used to move funds for a transfer.
     */
    @JsonIgnore
    public TransferType transferType() {
        return transferType;
    }

    @JsonIgnore
    public OffsetDateTime createdOn() {
        return createdOn;
    }

    @JsonIgnore
    public TransferSource source() {
        return source;
    }

    @JsonIgnore
    public TransferDestination destination() {
        return destination;
    }

    @JsonIgnore
    public Optional<OffsetDateTime> completedOn() {
        return completedOn;
    }

    /**
     * Status of a transfer.
     */
    @JsonIgnore
    public TransferStatus status() {
        return status;
    }

    /**
     * Reason for a transfer's failure.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<TransferFailureReason> failureReason() {
        return (Optional<TransferFailureReason>) failureReason;
    }

    @JsonIgnore
    public AmountDecimal amount() {
        return amount;
    }

    /**
     * An optional description of the transfer that is used on receipts and for your own internal use.
     */
    @JsonIgnore
    public Optional<String> description() {
        return description;
    }

    /**
     * Free-form key-value pair list. Useful for storing information that is not captured elsewhere.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Map<String, String>> metadata() {
        return (Optional<Map<String, String>>) metadata;
    }

    /**
     * Total or markup fee.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<FacilitatorFee> facilitatorFee() {
        return (Optional<FacilitatorFee>) facilitatorFee;
    }

    /**
     * Fees charged to your platform account for transfers.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<AmountDecimal> moovFee() {
        return (Optional<AmountDecimal>) moovFee;
    }

    /**
     * Processing and pass-through costs that add up to the moovFee.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<MoovFeeDetails> moovFeeDetails() {
        return (Optional<MoovFeeDetails>) moovFeeDetails;
    }

    /**
     * Fees charged to accounts involved in the transfer.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<MoovFee>> moovFees() {
        return (Optional<List<MoovFee>>) moovFees;
    }

    @JsonIgnore
    public Optional<String> groupID() {
        return groupID;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<AmountDecimal> refundedAmount() {
        return (Optional<AmountDecimal>) refundedAmount;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<AmountDecimal> disputedAmount() {
        return (Optional<AmountDecimal>) disputedAmount;
    }

    /**
     * ID of the sweep that created this transfer.
     */
    @JsonIgnore
    public Optional<String> sweepID() {
        return sweepID;
    }

    @JsonIgnore
    public Optional<String> scheduleID() {
        return scheduleID;
    }

    @JsonIgnore
    public Optional<String> occurrenceID() {
        return occurrenceID;
    }

    @JsonIgnore
    public Optional<String> paymentLinkCode() {
        return paymentLinkCode;
    }

    /**
     * Optional alias from a foreign/external system which can be used to reference this resource.
     */
    @JsonIgnore
    public Optional<String> foreignID() {
        return foreignID;
    }

    /**
     * An optional collection of line items for a transfer.
     * When line items are provided, their total plus tax must equal the transfer amount.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<TransferLineItems> lineItems() {
        return (Optional<TransferLineItems>) lineItems;
    }

    /**
     * ID of the invoice that the transfer is associated with.
     */
    @JsonIgnore
    public Optional<String> invoiceID() {
        return invoiceID;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<TransferAmountDetails> amountDetails() {
        return (Optional<TransferAmountDetails>) amountDetails;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<TransferAuthorization> authorization() {
        return (Optional<TransferAuthorization>) authorization;
    }

    @JsonIgnore
    public TransferRailOptions options() {
        return options;
    }

    @JsonIgnore
    public TransferProcessingDetails processingDetails() {
        return processingDetails;
    }

    public static Builder builder() {
        return new Builder();
    }


    public Transfer withTransferID(String transferID) {
        Utils.checkNotNull(transferID, "transferID");
        this.transferID = transferID;
        return this;
    }

    /**
     * The rail and direction used to move funds for a transfer.
     */
    public Transfer withTransferType(TransferType transferType) {
        Utils.checkNotNull(transferType, "transferType");
        this.transferType = transferType;
        return this;
    }

    public Transfer withCreatedOn(OffsetDateTime createdOn) {
        Utils.checkNotNull(createdOn, "createdOn");
        this.createdOn = createdOn;
        return this;
    }

    public Transfer withSource(TransferSource source) {
        Utils.checkNotNull(source, "source");
        this.source = source;
        return this;
    }

    public Transfer withDestination(TransferDestination destination) {
        Utils.checkNotNull(destination, "destination");
        this.destination = destination;
        return this;
    }

    public Transfer withCompletedOn(OffsetDateTime completedOn) {
        Utils.checkNotNull(completedOn, "completedOn");
        this.completedOn = Optional.ofNullable(completedOn);
        return this;
    }


    public Transfer withCompletedOn(Optional<OffsetDateTime> completedOn) {
        Utils.checkNotNull(completedOn, "completedOn");
        this.completedOn = completedOn;
        return this;
    }

    /**
     * Status of a transfer.
     */
    public Transfer withStatus(TransferStatus status) {
        Utils.checkNotNull(status, "status");
        this.status = status;
        return this;
    }

    /**
     * Reason for a transfer's failure.
     */
    public Transfer withFailureReason(TransferFailureReason failureReason) {
        Utils.checkNotNull(failureReason, "failureReason");
        this.failureReason = Optional.ofNullable(failureReason);
        return this;
    }


    /**
     * Reason for a transfer's failure.
     */
    public Transfer withFailureReason(Optional<? extends TransferFailureReason> failureReason) {
        Utils.checkNotNull(failureReason, "failureReason");
        this.failureReason = failureReason;
        return this;
    }

    public Transfer withAmount(AmountDecimal amount) {
        Utils.checkNotNull(amount, "amount");
        this.amount = amount;
        return this;
    }

    /**
     * An optional description of the transfer that is used on receipts and for your own internal use.
     */
    public Transfer withDescription(String description) {
        Utils.checkNotNull(description, "description");
        this.description = Optional.ofNullable(description);
        return this;
    }


    /**
     * An optional description of the transfer that is used on receipts and for your own internal use.
     */
    public Transfer withDescription(Optional<String> description) {
        Utils.checkNotNull(description, "description");
        this.description = description;
        return this;
    }

    /**
     * Free-form key-value pair list. Useful for storing information that is not captured elsewhere.
     */
    public Transfer withMetadata(Map<String, String> metadata) {
        Utils.checkNotNull(metadata, "metadata");
        this.metadata = Optional.ofNullable(metadata);
        return this;
    }


    /**
     * Free-form key-value pair list. Useful for storing information that is not captured elsewhere.
     */
    public Transfer withMetadata(Optional<? extends Map<String, String>> metadata) {
        Utils.checkNotNull(metadata, "metadata");
        this.metadata = metadata;
        return this;
    }

    /**
     * Total or markup fee.
     */
    public Transfer withFacilitatorFee(FacilitatorFee facilitatorFee) {
        Utils.checkNotNull(facilitatorFee, "facilitatorFee");
        this.facilitatorFee = Optional.ofNullable(facilitatorFee);
        return this;
    }


    /**
     * Total or markup fee.
     */
    public Transfer withFacilitatorFee(Optional<? extends FacilitatorFee> facilitatorFee) {
        Utils.checkNotNull(facilitatorFee, "facilitatorFee");
        this.facilitatorFee = facilitatorFee;
        return this;
    }

    /**
     * Fees charged to your platform account for transfers.
     */
    public Transfer withMoovFee(AmountDecimal moovFee) {
        Utils.checkNotNull(moovFee, "moovFee");
        this.moovFee = Optional.ofNullable(moovFee);
        return this;
    }


    /**
     * Fees charged to your platform account for transfers.
     */
    public Transfer withMoovFee(Optional<? extends AmountDecimal> moovFee) {
        Utils.checkNotNull(moovFee, "moovFee");
        this.moovFee = moovFee;
        return this;
    }

    /**
     * Processing and pass-through costs that add up to the moovFee.
     */
    public Transfer withMoovFeeDetails(MoovFeeDetails moovFeeDetails) {
        Utils.checkNotNull(moovFeeDetails, "moovFeeDetails");
        this.moovFeeDetails = Optional.ofNullable(moovFeeDetails);
        return this;
    }


    /**
     * Processing and pass-through costs that add up to the moovFee.
     */
    public Transfer withMoovFeeDetails(Optional<? extends MoovFeeDetails> moovFeeDetails) {
        Utils.checkNotNull(moovFeeDetails, "moovFeeDetails");
        this.moovFeeDetails = moovFeeDetails;
        return this;
    }

    /**
     * Fees charged to accounts involved in the transfer.
     */
    public Transfer withMoovFees(List<MoovFee> moovFees) {
        Utils.checkNotNull(moovFees, "moovFees");
        this.moovFees = Optional.ofNullable(moovFees);
        return this;
    }


    /**
     * Fees charged to accounts involved in the transfer.
     */
    public Transfer withMoovFees(Optional<? extends List<MoovFee>> moovFees) {
        Utils.checkNotNull(moovFees, "moovFees");
        this.moovFees = moovFees;
        return this;
    }

    public Transfer withGroupID(String groupID) {
        Utils.checkNotNull(groupID, "groupID");
        this.groupID = Optional.ofNullable(groupID);
        return this;
    }


    public Transfer withGroupID(Optional<String> groupID) {
        Utils.checkNotNull(groupID, "groupID");
        this.groupID = groupID;
        return this;
    }

    public Transfer withRefundedAmount(AmountDecimal refundedAmount) {
        Utils.checkNotNull(refundedAmount, "refundedAmount");
        this.refundedAmount = Optional.ofNullable(refundedAmount);
        return this;
    }


    public Transfer withRefundedAmount(Optional<? extends AmountDecimal> refundedAmount) {
        Utils.checkNotNull(refundedAmount, "refundedAmount");
        this.refundedAmount = refundedAmount;
        return this;
    }

    public Transfer withDisputedAmount(AmountDecimal disputedAmount) {
        Utils.checkNotNull(disputedAmount, "disputedAmount");
        this.disputedAmount = Optional.ofNullable(disputedAmount);
        return this;
    }


    public Transfer withDisputedAmount(Optional<? extends AmountDecimal> disputedAmount) {
        Utils.checkNotNull(disputedAmount, "disputedAmount");
        this.disputedAmount = disputedAmount;
        return this;
    }

    /**
     * ID of the sweep that created this transfer.
     */
    public Transfer withSweepID(String sweepID) {
        Utils.checkNotNull(sweepID, "sweepID");
        this.sweepID = Optional.ofNullable(sweepID);
        return this;
    }


    /**
     * ID of the sweep that created this transfer.
     */
    public Transfer withSweepID(Optional<String> sweepID) {
        Utils.checkNotNull(sweepID, "sweepID");
        this.sweepID = sweepID;
        return this;
    }

    public Transfer withScheduleID(String scheduleID) {
        Utils.checkNotNull(scheduleID, "scheduleID");
        this.scheduleID = Optional.ofNullable(scheduleID);
        return this;
    }


    public Transfer withScheduleID(Optional<String> scheduleID) {
        Utils.checkNotNull(scheduleID, "scheduleID");
        this.scheduleID = scheduleID;
        return this;
    }

    public Transfer withOccurrenceID(String occurrenceID) {
        Utils.checkNotNull(occurrenceID, "occurrenceID");
        this.occurrenceID = Optional.ofNullable(occurrenceID);
        return this;
    }


    public Transfer withOccurrenceID(Optional<String> occurrenceID) {
        Utils.checkNotNull(occurrenceID, "occurrenceID");
        this.occurrenceID = occurrenceID;
        return this;
    }

    public Transfer withPaymentLinkCode(String paymentLinkCode) {
        Utils.checkNotNull(paymentLinkCode, "paymentLinkCode");
        this.paymentLinkCode = Optional.ofNullable(paymentLinkCode);
        return this;
    }


    public Transfer withPaymentLinkCode(Optional<String> paymentLinkCode) {
        Utils.checkNotNull(paymentLinkCode, "paymentLinkCode");
        this.paymentLinkCode = paymentLinkCode;
        return this;
    }

    /**
     * Optional alias from a foreign/external system which can be used to reference this resource.
     */
    public Transfer withForeignID(String foreignID) {
        Utils.checkNotNull(foreignID, "foreignID");
        this.foreignID = Optional.ofNullable(foreignID);
        return this;
    }


    /**
     * Optional alias from a foreign/external system which can be used to reference this resource.
     */
    public Transfer withForeignID(Optional<String> foreignID) {
        Utils.checkNotNull(foreignID, "foreignID");
        this.foreignID = foreignID;
        return this;
    }

    /**
     * An optional collection of line items for a transfer.
     * When line items are provided, their total plus tax must equal the transfer amount.
     */
    public Transfer withLineItems(TransferLineItems lineItems) {
        Utils.checkNotNull(lineItems, "lineItems");
        this.lineItems = Optional.ofNullable(lineItems);
        return this;
    }


    /**
     * An optional collection of line items for a transfer.
     * When line items are provided, their total plus tax must equal the transfer amount.
     */
    public Transfer withLineItems(Optional<? extends TransferLineItems> lineItems) {
        Utils.checkNotNull(lineItems, "lineItems");
        this.lineItems = lineItems;
        return this;
    }

    /**
     * ID of the invoice that the transfer is associated with.
     */
    public Transfer withInvoiceID(String invoiceID) {
        Utils.checkNotNull(invoiceID, "invoiceID");
        this.invoiceID = Optional.ofNullable(invoiceID);
        return this;
    }


    /**
     * ID of the invoice that the transfer is associated with.
     */
    public Transfer withInvoiceID(Optional<String> invoiceID) {
        Utils.checkNotNull(invoiceID, "invoiceID");
        this.invoiceID = invoiceID;
        return this;
    }

    public Transfer withAmountDetails(TransferAmountDetails amountDetails) {
        Utils.checkNotNull(amountDetails, "amountDetails");
        this.amountDetails = Optional.ofNullable(amountDetails);
        return this;
    }


    public Transfer withAmountDetails(Optional<? extends TransferAmountDetails> amountDetails) {
        Utils.checkNotNull(amountDetails, "amountDetails");
        this.amountDetails = amountDetails;
        return this;
    }

    public Transfer withAuthorization(TransferAuthorization authorization) {
        Utils.checkNotNull(authorization, "authorization");
        this.authorization = Optional.ofNullable(authorization);
        return this;
    }


    public Transfer withAuthorization(Optional<? extends TransferAuthorization> authorization) {
        Utils.checkNotNull(authorization, "authorization");
        this.authorization = authorization;
        return this;
    }

    public Transfer withOptions(TransferRailOptions options) {
        Utils.checkNotNull(options, "options");
        this.options = options;
        return this;
    }

    public Transfer withProcessingDetails(TransferProcessingDetails processingDetails) {
        Utils.checkNotNull(processingDetails, "processingDetails");
        this.processingDetails = processingDetails;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Transfer other = (Transfer) o;
        return 
            Utils.enhancedDeepEquals(this.transferID, other.transferID) &&
            Utils.enhancedDeepEquals(this.transferType, other.transferType) &&
            Utils.enhancedDeepEquals(this.createdOn, other.createdOn) &&
            Utils.enhancedDeepEquals(this.source, other.source) &&
            Utils.enhancedDeepEquals(this.destination, other.destination) &&
            Utils.enhancedDeepEquals(this.completedOn, other.completedOn) &&
            Utils.enhancedDeepEquals(this.status, other.status) &&
            Utils.enhancedDeepEquals(this.failureReason, other.failureReason) &&
            Utils.enhancedDeepEquals(this.amount, other.amount) &&
            Utils.enhancedDeepEquals(this.description, other.description) &&
            Utils.enhancedDeepEquals(this.metadata, other.metadata) &&
            Utils.enhancedDeepEquals(this.facilitatorFee, other.facilitatorFee) &&
            Utils.enhancedDeepEquals(this.moovFee, other.moovFee) &&
            Utils.enhancedDeepEquals(this.moovFeeDetails, other.moovFeeDetails) &&
            Utils.enhancedDeepEquals(this.moovFees, other.moovFees) &&
            Utils.enhancedDeepEquals(this.groupID, other.groupID) &&
            Utils.enhancedDeepEquals(this.refundedAmount, other.refundedAmount) &&
            Utils.enhancedDeepEquals(this.disputedAmount, other.disputedAmount) &&
            Utils.enhancedDeepEquals(this.sweepID, other.sweepID) &&
            Utils.enhancedDeepEquals(this.scheduleID, other.scheduleID) &&
            Utils.enhancedDeepEquals(this.occurrenceID, other.occurrenceID) &&
            Utils.enhancedDeepEquals(this.paymentLinkCode, other.paymentLinkCode) &&
            Utils.enhancedDeepEquals(this.foreignID, other.foreignID) &&
            Utils.enhancedDeepEquals(this.lineItems, other.lineItems) &&
            Utils.enhancedDeepEquals(this.invoiceID, other.invoiceID) &&
            Utils.enhancedDeepEquals(this.amountDetails, other.amountDetails) &&
            Utils.enhancedDeepEquals(this.authorization, other.authorization) &&
            Utils.enhancedDeepEquals(this.options, other.options) &&
            Utils.enhancedDeepEquals(this.processingDetails, other.processingDetails);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            transferID, transferType, createdOn,
            source, destination, completedOn,
            status, failureReason, amount,
            description, metadata, facilitatorFee,
            moovFee, moovFeeDetails, moovFees,
            groupID, refundedAmount, disputedAmount,
            sweepID, scheduleID, occurrenceID,
            paymentLinkCode, foreignID, lineItems,
            invoiceID, amountDetails, authorization,
            options, processingDetails);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Transfer.class,
                "transferID", transferID,
                "transferType", transferType,
                "createdOn", createdOn,
                "source", source,
                "destination", destination,
                "completedOn", completedOn,
                "status", status,
                "failureReason", failureReason,
                "amount", amount,
                "description", description,
                "metadata", metadata,
                "facilitatorFee", facilitatorFee,
                "moovFee", moovFee,
                "moovFeeDetails", moovFeeDetails,
                "moovFees", moovFees,
                "groupID", groupID,
                "refundedAmount", refundedAmount,
                "disputedAmount", disputedAmount,
                "sweepID", sweepID,
                "scheduleID", scheduleID,
                "occurrenceID", occurrenceID,
                "paymentLinkCode", paymentLinkCode,
                "foreignID", foreignID,
                "lineItems", lineItems,
                "invoiceID", invoiceID,
                "amountDetails", amountDetails,
                "authorization", authorization,
                "options", options,
                "processingDetails", processingDetails);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String transferID;

        private TransferType transferType;

        private OffsetDateTime createdOn;

        private TransferSource source;

        private TransferDestination destination;

        private Optional<OffsetDateTime> completedOn = Optional.empty();

        private TransferStatus status;

        private Optional<? extends TransferFailureReason> failureReason = Optional.empty();

        private AmountDecimal amount;

        private Optional<String> description = Optional.empty();

        private Optional<? extends Map<String, String>> metadata = Optional.empty();

        private Optional<? extends FacilitatorFee> facilitatorFee = Optional.empty();

        private Optional<? extends AmountDecimal> moovFee = Optional.empty();

        private Optional<? extends MoovFeeDetails> moovFeeDetails = Optional.empty();

        private Optional<? extends List<MoovFee>> moovFees = Optional.empty();

        private Optional<String> groupID = Optional.empty();

        private Optional<? extends AmountDecimal> refundedAmount = Optional.empty();

        private Optional<? extends AmountDecimal> disputedAmount = Optional.empty();

        private Optional<String> sweepID = Optional.empty();

        private Optional<String> scheduleID = Optional.empty();

        private Optional<String> occurrenceID = Optional.empty();

        private Optional<String> paymentLinkCode = Optional.empty();

        private Optional<String> foreignID = Optional.empty();

        private Optional<? extends TransferLineItems> lineItems = Optional.empty();

        private Optional<String> invoiceID = Optional.empty();

        private Optional<? extends TransferAmountDetails> amountDetails = Optional.empty();

        private Optional<? extends TransferAuthorization> authorization = Optional.empty();

        private TransferRailOptions options;

        private TransferProcessingDetails processingDetails;

        private Builder() {
          // force use of static builder() method
        }


        public Builder transferID(String transferID) {
            Utils.checkNotNull(transferID, "transferID");
            this.transferID = transferID;
            return this;
        }


        /**
         * The rail and direction used to move funds for a transfer.
         */
        public Builder transferType(TransferType transferType) {
            Utils.checkNotNull(transferType, "transferType");
            this.transferType = transferType;
            return this;
        }


        public Builder createdOn(OffsetDateTime createdOn) {
            Utils.checkNotNull(createdOn, "createdOn");
            this.createdOn = createdOn;
            return this;
        }


        public Builder source(TransferSource source) {
            Utils.checkNotNull(source, "source");
            this.source = source;
            return this;
        }


        public Builder destination(TransferDestination destination) {
            Utils.checkNotNull(destination, "destination");
            this.destination = destination;
            return this;
        }


        public Builder completedOn(OffsetDateTime completedOn) {
            Utils.checkNotNull(completedOn, "completedOn");
            this.completedOn = Optional.ofNullable(completedOn);
            return this;
        }

        public Builder completedOn(Optional<OffsetDateTime> completedOn) {
            Utils.checkNotNull(completedOn, "completedOn");
            this.completedOn = completedOn;
            return this;
        }


        /**
         * Status of a transfer.
         */
        public Builder status(TransferStatus status) {
            Utils.checkNotNull(status, "status");
            this.status = status;
            return this;
        }


        /**
         * Reason for a transfer's failure.
         */
        public Builder failureReason(TransferFailureReason failureReason) {
            Utils.checkNotNull(failureReason, "failureReason");
            this.failureReason = Optional.ofNullable(failureReason);
            return this;
        }

        /**
         * Reason for a transfer's failure.
         */
        public Builder failureReason(Optional<? extends TransferFailureReason> failureReason) {
            Utils.checkNotNull(failureReason, "failureReason");
            this.failureReason = failureReason;
            return this;
        }


        public Builder amount(AmountDecimal amount) {
            Utils.checkNotNull(amount, "amount");
            this.amount = amount;
            return this;
        }


        /**
         * An optional description of the transfer that is used on receipts and for your own internal use.
         */
        public Builder description(String description) {
            Utils.checkNotNull(description, "description");
            this.description = Optional.ofNullable(description);
            return this;
        }

        /**
         * An optional description of the transfer that is used on receipts and for your own internal use.
         */
        public Builder description(Optional<String> description) {
            Utils.checkNotNull(description, "description");
            this.description = description;
            return this;
        }


        /**
         * Free-form key-value pair list. Useful for storing information that is not captured elsewhere.
         */
        public Builder metadata(Map<String, String> metadata) {
            Utils.checkNotNull(metadata, "metadata");
            this.metadata = Optional.ofNullable(metadata);
            return this;
        }

        /**
         * Free-form key-value pair list. Useful for storing information that is not captured elsewhere.
         */
        public Builder metadata(Optional<? extends Map<String, String>> metadata) {
            Utils.checkNotNull(metadata, "metadata");
            this.metadata = metadata;
            return this;
        }


        /**
         * Total or markup fee.
         */
        public Builder facilitatorFee(FacilitatorFee facilitatorFee) {
            Utils.checkNotNull(facilitatorFee, "facilitatorFee");
            this.facilitatorFee = Optional.ofNullable(facilitatorFee);
            return this;
        }

        /**
         * Total or markup fee.
         */
        public Builder facilitatorFee(Optional<? extends FacilitatorFee> facilitatorFee) {
            Utils.checkNotNull(facilitatorFee, "facilitatorFee");
            this.facilitatorFee = facilitatorFee;
            return this;
        }


        /**
         * Fees charged to your platform account for transfers.
         */
        public Builder moovFee(AmountDecimal moovFee) {
            Utils.checkNotNull(moovFee, "moovFee");
            this.moovFee = Optional.ofNullable(moovFee);
            return this;
        }

        /**
         * Fees charged to your platform account for transfers.
         */
        public Builder moovFee(Optional<? extends AmountDecimal> moovFee) {
            Utils.checkNotNull(moovFee, "moovFee");
            this.moovFee = moovFee;
            return this;
        }


        /**
         * Processing and pass-through costs that add up to the moovFee.
         */
        public Builder moovFeeDetails(MoovFeeDetails moovFeeDetails) {
            Utils.checkNotNull(moovFeeDetails, "moovFeeDetails");
            this.moovFeeDetails = Optional.ofNullable(moovFeeDetails);
            return this;
        }

        /**
         * Processing and pass-through costs that add up to the moovFee.
         */
        public Builder moovFeeDetails(Optional<? extends MoovFeeDetails> moovFeeDetails) {
            Utils.checkNotNull(moovFeeDetails, "moovFeeDetails");
            this.moovFeeDetails = moovFeeDetails;
            return this;
        }


        /**
         * Fees charged to accounts involved in the transfer.
         */
        public Builder moovFees(List<MoovFee> moovFees) {
            Utils.checkNotNull(moovFees, "moovFees");
            this.moovFees = Optional.ofNullable(moovFees);
            return this;
        }

        /**
         * Fees charged to accounts involved in the transfer.
         */
        public Builder moovFees(Optional<? extends List<MoovFee>> moovFees) {
            Utils.checkNotNull(moovFees, "moovFees");
            this.moovFees = moovFees;
            return this;
        }


        public Builder groupID(String groupID) {
            Utils.checkNotNull(groupID, "groupID");
            this.groupID = Optional.ofNullable(groupID);
            return this;
        }

        public Builder groupID(Optional<String> groupID) {
            Utils.checkNotNull(groupID, "groupID");
            this.groupID = groupID;
            return this;
        }


        public Builder refundedAmount(AmountDecimal refundedAmount) {
            Utils.checkNotNull(refundedAmount, "refundedAmount");
            this.refundedAmount = Optional.ofNullable(refundedAmount);
            return this;
        }

        public Builder refundedAmount(Optional<? extends AmountDecimal> refundedAmount) {
            Utils.checkNotNull(refundedAmount, "refundedAmount");
            this.refundedAmount = refundedAmount;
            return this;
        }


        public Builder disputedAmount(AmountDecimal disputedAmount) {
            Utils.checkNotNull(disputedAmount, "disputedAmount");
            this.disputedAmount = Optional.ofNullable(disputedAmount);
            return this;
        }

        public Builder disputedAmount(Optional<? extends AmountDecimal> disputedAmount) {
            Utils.checkNotNull(disputedAmount, "disputedAmount");
            this.disputedAmount = disputedAmount;
            return this;
        }


        /**
         * ID of the sweep that created this transfer.
         */
        public Builder sweepID(String sweepID) {
            Utils.checkNotNull(sweepID, "sweepID");
            this.sweepID = Optional.ofNullable(sweepID);
            return this;
        }

        /**
         * ID of the sweep that created this transfer.
         */
        public Builder sweepID(Optional<String> sweepID) {
            Utils.checkNotNull(sweepID, "sweepID");
            this.sweepID = sweepID;
            return this;
        }


        public Builder scheduleID(String scheduleID) {
            Utils.checkNotNull(scheduleID, "scheduleID");
            this.scheduleID = Optional.ofNullable(scheduleID);
            return this;
        }

        public Builder scheduleID(Optional<String> scheduleID) {
            Utils.checkNotNull(scheduleID, "scheduleID");
            this.scheduleID = scheduleID;
            return this;
        }


        public Builder occurrenceID(String occurrenceID) {
            Utils.checkNotNull(occurrenceID, "occurrenceID");
            this.occurrenceID = Optional.ofNullable(occurrenceID);
            return this;
        }

        public Builder occurrenceID(Optional<String> occurrenceID) {
            Utils.checkNotNull(occurrenceID, "occurrenceID");
            this.occurrenceID = occurrenceID;
            return this;
        }


        public Builder paymentLinkCode(String paymentLinkCode) {
            Utils.checkNotNull(paymentLinkCode, "paymentLinkCode");
            this.paymentLinkCode = Optional.ofNullable(paymentLinkCode);
            return this;
        }

        public Builder paymentLinkCode(Optional<String> paymentLinkCode) {
            Utils.checkNotNull(paymentLinkCode, "paymentLinkCode");
            this.paymentLinkCode = paymentLinkCode;
            return this;
        }


        /**
         * Optional alias from a foreign/external system which can be used to reference this resource.
         */
        public Builder foreignID(String foreignID) {
            Utils.checkNotNull(foreignID, "foreignID");
            this.foreignID = Optional.ofNullable(foreignID);
            return this;
        }

        /**
         * Optional alias from a foreign/external system which can be used to reference this resource.
         */
        public Builder foreignID(Optional<String> foreignID) {
            Utils.checkNotNull(foreignID, "foreignID");
            this.foreignID = foreignID;
            return this;
        }


        /**
         * An optional collection of line items for a transfer.
         * When line items are provided, their total plus tax must equal the transfer amount.
         */
        public Builder lineItems(TransferLineItems lineItems) {
            Utils.checkNotNull(lineItems, "lineItems");
            this.lineItems = Optional.ofNullable(lineItems);
            return this;
        }

        /**
         * An optional collection of line items for a transfer.
         * When line items are provided, their total plus tax must equal the transfer amount.
         */
        public Builder lineItems(Optional<? extends TransferLineItems> lineItems) {
            Utils.checkNotNull(lineItems, "lineItems");
            this.lineItems = lineItems;
            return this;
        }


        /**
         * ID of the invoice that the transfer is associated with.
         */
        public Builder invoiceID(String invoiceID) {
            Utils.checkNotNull(invoiceID, "invoiceID");
            this.invoiceID = Optional.ofNullable(invoiceID);
            return this;
        }

        /**
         * ID of the invoice that the transfer is associated with.
         */
        public Builder invoiceID(Optional<String> invoiceID) {
            Utils.checkNotNull(invoiceID, "invoiceID");
            this.invoiceID = invoiceID;
            return this;
        }


        public Builder amountDetails(TransferAmountDetails amountDetails) {
            Utils.checkNotNull(amountDetails, "amountDetails");
            this.amountDetails = Optional.ofNullable(amountDetails);
            return this;
        }

        public Builder amountDetails(Optional<? extends TransferAmountDetails> amountDetails) {
            Utils.checkNotNull(amountDetails, "amountDetails");
            this.amountDetails = amountDetails;
            return this;
        }


        public Builder authorization(TransferAuthorization authorization) {
            Utils.checkNotNull(authorization, "authorization");
            this.authorization = Optional.ofNullable(authorization);
            return this;
        }

        public Builder authorization(Optional<? extends TransferAuthorization> authorization) {
            Utils.checkNotNull(authorization, "authorization");
            this.authorization = authorization;
            return this;
        }


        public Builder options(TransferRailOptions options) {
            Utils.checkNotNull(options, "options");
            this.options = options;
            return this;
        }


        public Builder processingDetails(TransferProcessingDetails processingDetails) {
            Utils.checkNotNull(processingDetails, "processingDetails");
            this.processingDetails = processingDetails;
            return this;
        }

        public Transfer build() {

            return new Transfer(
                transferID, transferType, createdOn,
                source, destination, completedOn,
                status, failureReason, amount,
                description, metadata, facilitatorFee,
                moovFee, moovFeeDetails, moovFees,
                groupID, refundedAmount, disputedAmount,
                sweepID, scheduleID, occurrenceID,
                paymentLinkCode, foreignID, lineItems,
                invoiceID, amountDetails, authorization,
                options, processingDetails);
        }

    }
}
