/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.moov.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.moov.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Map;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;


public class UpdateIssuedCard {
    /**
     * Updates the state of a Moov issued card.
     * - `active`: Reactivates a frozen card so it can approve authorizations again.
     * - `frozen`: Temporarily suspends the card so it cannot approve authorizations. A card can be moved
     * between `frozen` and `active` at will until it is `closed`, which is a terminal state.
     * - `closed`: The card is permanently deactivated and cannot approve authorizations. A card can be
     * closed by request or when it expires.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("state")
    private Optional<? extends UpdateIssuedCardState> state;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("nickname")
    private JsonNullable<String> nickname;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("metadata")
    private JsonNullable<? extends Map<String, String>> metadata;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("billingAddress")
    private JsonNullable<? extends BillingAddress> billingAddress;

    /**
     * Mutable spend controls for the card.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("controls")
    private Optional<? extends UpdateIssuingControls> controls;

    @JsonCreator
    public UpdateIssuedCard(
            @JsonProperty("state") Optional<? extends UpdateIssuedCardState> state,
            @JsonProperty("nickname") JsonNullable<String> nickname,
            @JsonProperty("metadata") JsonNullable<? extends Map<String, String>> metadata,
            @JsonProperty("billingAddress") JsonNullable<? extends BillingAddress> billingAddress,
            @JsonProperty("controls") Optional<? extends UpdateIssuingControls> controls) {
        Utils.checkNotNull(state, "state");
        Utils.checkNotNull(nickname, "nickname");
        Utils.checkNotNull(metadata, "metadata");
        Utils.checkNotNull(billingAddress, "billingAddress");
        Utils.checkNotNull(controls, "controls");
        this.state = state;
        this.nickname = nickname;
        this.metadata = metadata;
        this.billingAddress = billingAddress;
        this.controls = controls;
    }
    
    public UpdateIssuedCard() {
        this(Optional.empty(), JsonNullable.undefined(), JsonNullable.undefined(),
            JsonNullable.undefined(), Optional.empty());
    }

    /**
     * Updates the state of a Moov issued card.
     * - `active`: Reactivates a frozen card so it can approve authorizations again.
     * - `frozen`: Temporarily suspends the card so it cannot approve authorizations. A card can be moved
     * between `frozen` and `active` at will until it is `closed`, which is a terminal state.
     * - `closed`: The card is permanently deactivated and cannot approve authorizations. A card can be
     * closed by request or when it expires.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<UpdateIssuedCardState> state() {
        return (Optional<UpdateIssuedCardState>) state;
    }

    @JsonIgnore
    public JsonNullable<String> nickname() {
        return nickname;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<Map<String, String>> metadata() {
        return (JsonNullable<Map<String, String>>) metadata;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<BillingAddress> billingAddress() {
        return (JsonNullable<BillingAddress>) billingAddress;
    }

    /**
     * Mutable spend controls for the card.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<UpdateIssuingControls> controls() {
        return (Optional<UpdateIssuingControls>) controls;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Updates the state of a Moov issued card.
     * - `active`: Reactivates a frozen card so it can approve authorizations again.
     * - `frozen`: Temporarily suspends the card so it cannot approve authorizations. A card can be moved
     * between `frozen` and `active` at will until it is `closed`, which is a terminal state.
     * - `closed`: The card is permanently deactivated and cannot approve authorizations. A card can be
     * closed by request or when it expires.
     */
    public UpdateIssuedCard withState(UpdateIssuedCardState state) {
        Utils.checkNotNull(state, "state");
        this.state = Optional.ofNullable(state);
        return this;
    }


    /**
     * Updates the state of a Moov issued card.
     * - `active`: Reactivates a frozen card so it can approve authorizations again.
     * - `frozen`: Temporarily suspends the card so it cannot approve authorizations. A card can be moved
     * between `frozen` and `active` at will until it is `closed`, which is a terminal state.
     * - `closed`: The card is permanently deactivated and cannot approve authorizations. A card can be
     * closed by request or when it expires.
     */
    public UpdateIssuedCard withState(Optional<? extends UpdateIssuedCardState> state) {
        Utils.checkNotNull(state, "state");
        this.state = state;
        return this;
    }

    public UpdateIssuedCard withNickname(String nickname) {
        Utils.checkNotNull(nickname, "nickname");
        this.nickname = JsonNullable.of(nickname);
        return this;
    }

    public UpdateIssuedCard withNickname(JsonNullable<String> nickname) {
        Utils.checkNotNull(nickname, "nickname");
        this.nickname = nickname;
        return this;
    }

    public UpdateIssuedCard withMetadata(Map<String, String> metadata) {
        Utils.checkNotNull(metadata, "metadata");
        this.metadata = JsonNullable.of(metadata);
        return this;
    }

    public UpdateIssuedCard withMetadata(JsonNullable<? extends Map<String, String>> metadata) {
        Utils.checkNotNull(metadata, "metadata");
        this.metadata = metadata;
        return this;
    }

    public UpdateIssuedCard withBillingAddress(BillingAddress billingAddress) {
        Utils.checkNotNull(billingAddress, "billingAddress");
        this.billingAddress = JsonNullable.of(billingAddress);
        return this;
    }

    public UpdateIssuedCard withBillingAddress(JsonNullable<? extends BillingAddress> billingAddress) {
        Utils.checkNotNull(billingAddress, "billingAddress");
        this.billingAddress = billingAddress;
        return this;
    }

    /**
     * Mutable spend controls for the card.
     */
    public UpdateIssuedCard withControls(UpdateIssuingControls controls) {
        Utils.checkNotNull(controls, "controls");
        this.controls = Optional.ofNullable(controls);
        return this;
    }


    /**
     * Mutable spend controls for the card.
     */
    public UpdateIssuedCard withControls(Optional<? extends UpdateIssuingControls> controls) {
        Utils.checkNotNull(controls, "controls");
        this.controls = controls;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateIssuedCard other = (UpdateIssuedCard) o;
        return 
            Utils.enhancedDeepEquals(this.state, other.state) &&
            Utils.enhancedDeepEquals(this.nickname, other.nickname) &&
            Utils.enhancedDeepEquals(this.metadata, other.metadata) &&
            Utils.enhancedDeepEquals(this.billingAddress, other.billingAddress) &&
            Utils.enhancedDeepEquals(this.controls, other.controls);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            state, nickname, metadata,
            billingAddress, controls);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateIssuedCard.class,
                "state", state,
                "nickname", nickname,
                "metadata", metadata,
                "billingAddress", billingAddress,
                "controls", controls);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends UpdateIssuedCardState> state = Optional.empty();

        private JsonNullable<String> nickname = JsonNullable.undefined();

        private JsonNullable<? extends Map<String, String>> metadata = JsonNullable.undefined();

        private JsonNullable<? extends BillingAddress> billingAddress = JsonNullable.undefined();

        private Optional<? extends UpdateIssuingControls> controls = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Updates the state of a Moov issued card.
         * - `active`: Reactivates a frozen card so it can approve authorizations again.
         * - `frozen`: Temporarily suspends the card so it cannot approve authorizations. A card can be moved
         * between `frozen` and `active` at will until it is `closed`, which is a terminal state.
         * - `closed`: The card is permanently deactivated and cannot approve authorizations. A card can be
         * closed by request or when it expires.
         */
        public Builder state(UpdateIssuedCardState state) {
            Utils.checkNotNull(state, "state");
            this.state = Optional.ofNullable(state);
            return this;
        }

        /**
         * Updates the state of a Moov issued card.
         * - `active`: Reactivates a frozen card so it can approve authorizations again.
         * - `frozen`: Temporarily suspends the card so it cannot approve authorizations. A card can be moved
         * between `frozen` and `active` at will until it is `closed`, which is a terminal state.
         * - `closed`: The card is permanently deactivated and cannot approve authorizations. A card can be
         * closed by request or when it expires.
         */
        public Builder state(Optional<? extends UpdateIssuedCardState> state) {
            Utils.checkNotNull(state, "state");
            this.state = state;
            return this;
        }


        public Builder nickname(String nickname) {
            Utils.checkNotNull(nickname, "nickname");
            this.nickname = JsonNullable.of(nickname);
            return this;
        }

        public Builder nickname(JsonNullable<String> nickname) {
            Utils.checkNotNull(nickname, "nickname");
            this.nickname = nickname;
            return this;
        }


        public Builder metadata(Map<String, String> metadata) {
            Utils.checkNotNull(metadata, "metadata");
            this.metadata = JsonNullable.of(metadata);
            return this;
        }

        public Builder metadata(JsonNullable<? extends Map<String, String>> metadata) {
            Utils.checkNotNull(metadata, "metadata");
            this.metadata = metadata;
            return this;
        }


        public Builder billingAddress(BillingAddress billingAddress) {
            Utils.checkNotNull(billingAddress, "billingAddress");
            this.billingAddress = JsonNullable.of(billingAddress);
            return this;
        }

        public Builder billingAddress(JsonNullable<? extends BillingAddress> billingAddress) {
            Utils.checkNotNull(billingAddress, "billingAddress");
            this.billingAddress = billingAddress;
            return this;
        }


        /**
         * Mutable spend controls for the card.
         */
        public Builder controls(UpdateIssuingControls controls) {
            Utils.checkNotNull(controls, "controls");
            this.controls = Optional.ofNullable(controls);
            return this;
        }

        /**
         * Mutable spend controls for the card.
         */
        public Builder controls(Optional<? extends UpdateIssuingControls> controls) {
            Utils.checkNotNull(controls, "controls");
            this.controls = controls;
            return this;
        }

        public UpdateIssuedCard build() {

            return new UpdateIssuedCard(
                state, nickname, metadata,
                billingAddress, controls);
        }

    }
}
