/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.moov.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.moov.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;


public class WebhookBillingStatementCreated {

    @JsonProperty("accountID")
    private String accountID;


    @JsonProperty("statementID")
    private String statementID;

    @JsonCreator
    public WebhookBillingStatementCreated(
            @JsonProperty("accountID") String accountID,
            @JsonProperty("statementID") String statementID) {
        Utils.checkNotNull(accountID, "accountID");
        Utils.checkNotNull(statementID, "statementID");
        this.accountID = accountID;
        this.statementID = statementID;
    }

    @JsonIgnore
    public String accountID() {
        return accountID;
    }

    @JsonIgnore
    public String statementID() {
        return statementID;
    }

    public static Builder builder() {
        return new Builder();
    }


    public WebhookBillingStatementCreated withAccountID(String accountID) {
        Utils.checkNotNull(accountID, "accountID");
        this.accountID = accountID;
        return this;
    }

    public WebhookBillingStatementCreated withStatementID(String statementID) {
        Utils.checkNotNull(statementID, "statementID");
        this.statementID = statementID;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        WebhookBillingStatementCreated other = (WebhookBillingStatementCreated) o;
        return 
            Utils.enhancedDeepEquals(this.accountID, other.accountID) &&
            Utils.enhancedDeepEquals(this.statementID, other.statementID);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            accountID, statementID);
    }
    
    @Override
    public String toString() {
        return Utils.toString(WebhookBillingStatementCreated.class,
                "accountID", accountID,
                "statementID", statementID);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String accountID;

        private String statementID;

        private Builder() {
          // force use of static builder() method
        }


        public Builder accountID(String accountID) {
            Utils.checkNotNull(accountID, "accountID");
            this.accountID = accountID;
            return this;
        }


        public Builder statementID(String statementID) {
            Utils.checkNotNull(statementID, "statementID");
            this.statementID = statementID;
            return this;
        }

        public WebhookBillingStatementCreated build() {

            return new WebhookBillingStatementCreated(
                accountID, statementID);
        }

    }
}
